"""
Auto-generated snapshot — 2026-05
Total funds: 58
Generated: 2026-05-28 23:49
Source: MFData.in API + curated fallback
"""

SNAPSHOT_DATE = "2026-05"

SNAPSHOT_SCHEMES = {
    -9: {
        "name": "ABSL Frontline Equity Fund",
        "amc": "Aditya Birla Sun Life",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.4,
            "ICICI Bank": 7.8,
            "Infosys": 6.5,
            "Reliance Industries": 6.2,
            "TCS": 5.1,
            "Larsen & Toubro": 4.5,
            "ITC": 4.0,
            "Bharti Airtel": 3.6,
            "State Bank of India": 3.2,
            "Bajaj Finance": 2.9,
            "Axis Bank": 2.6,
            "Kotak Mahindra Bank": 2.3,
            "HCL Technologies": 2.1,
            "Hindustan Unilever": 1.9,
            "Maruti Suzuki": 1.7,
            "Sun Pharma": 1.6,
            "NTPC": 1.4,
            "Titan Company": 1.3,
            "Wipro": 1.2,
            "UltraTech Cement": 1.1,
        },
    },
    -44: {
        "name": "ABSL Tax Relief 96",
        "amc": "Aditya Birla Sun Life",
        "category": "ELSS",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 8.5,
            "ICICI Bank": 7.2,
            "Infosys": 6.0,
            "Reliance Industries": 5.5,
            "TCS": 4.8,
            "Larsen & Toubro": 4.2,
            "ITC": 3.8,
            "Bharti Airtel": 3.4,
            "State Bank of India": 3.0,
            "Bajaj Finance": 2.7,
            "Axis Bank": 2.4,
            "Kotak Mahindra Bank": 2.1,
            "HCL Technologies": 1.9,
            "Hindustan Unilever": 1.7,
            "Sun Pharma": 1.5,
            "Maruti Suzuki": 1.4,
            "Titan Company": 1.3,
            "NTPC": 1.2,
            "Wipro": 1.1,
            "UltraTech Cement": 1.0,
        },
    },
    -1: {
        "name": "Axis Bluechip Fund",
        "amc": "Axis",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.8,
            "ICICI Bank": 8.5,
            "Infosys": 7.2,
            "Reliance Industries": 6.8,
            "TCS": 5.9,
            "Bajaj Finance": 4.8,
            "Kotak Mahindra Bank": 4.2,
            "Larsen & Toubro": 3.9,
            "HCL Technologies": 3.5,
            "Bharti Airtel": 3.2,
            "Asian Paints": 2.8,
            "Titan Company": 2.6,
            "Maruti Suzuki": 2.4,
            "Hindustan Unilever": 2.3,
            "Avenue Supermarts": 2.1,
            "Sun Pharma": 1.9,
            "Divi's Laboratories": 1.8,
            "Nestle India": 1.7,
            "Wipro": 1.5,
            "SBI Life Insurance": 1.3,
        },
    },
    -37: {
        "name": "Axis Focused 25 Fund",
        "amc": "Axis",
        "category": "Focused Fund",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.5,
            "ICICI Bank": 8.0,
            "Infosys": 7.2,
            "Bajaj Finance": 6.5,
            "TCS": 5.8,
            "Kotak Mahindra Bank": 5.0,
            "Reliance Industries": 4.5,
            "Bharti Airtel": 4.0,
            "Larsen & Toubro": 3.5,
            "Avenue Supermarts": 3.0,
            "HCL Technologies": 2.8,
            "Titan Company": 2.5,
            "Asian Paints": 2.3,
            "Hindustan Unilever": 2.1,
            "Divi's Laboratories": 1.9,
            "Maruti Suzuki": 1.8,
            "Nestle India": 1.7,
            "Sun Pharma": 1.5,
            "SBI Life Insurance": 1.4,
            "Wipro": 1.2,
        },
    },
    -40: {
        "name": "Axis Long Term Equity Fund",
        "amc": "Axis",
        "category": "ELSS",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 8.8,
            "ICICI Bank": 7.5,
            "Infosys": 6.8,
            "Bajaj Finance": 5.2,
            "TCS": 4.8,
            "Kotak Mahindra Bank": 4.1,
            "Reliance Industries": 3.8,
            "Bharti Airtel": 3.4,
            "Larsen & Toubro": 3.0,
            "Avenue Supermarts": 2.7,
            "HCL Technologies": 2.5,
            "Titan Company": 2.3,
            "Asian Paints": 2.1,
            "Hindustan Unilever": 1.9,
            "Divi's Laboratories": 1.7,
            "Maruti Suzuki": 1.5,
            "Sun Pharma": 1.3,
            "Nestle India": 1.2,
            "SBI Life Insurance": 1.1,
            "Wipro": 1.0,
        },
    },
    -11: {
        "name": "Axis Midcap Fund",
        "amc": "Axis",
        "category": "Mid Cap",
        "month": "2026-05",
        "holdings": {
            "Persistent Systems": 5.2,
            "Cholamandalam Inv": 4.8,
            "Voltas": 4.3,
            "Federal Bank": 3.9,
            "Coforge": 3.6,
            "Sundaram Finance": 3.3,
            "Astral": 3.1,
            "Supreme Industries": 2.9,
            "Trent": 2.7,
            "PI Industries": 2.5,
            "APL Apollo Tubes": 2.3,
            "Dalmia Bharat": 2.1,
            "Mphasis": 2.0,
            "Schaeffler India": 1.9,
            "Page Industries": 1.8,
            "Indian Hotels": 1.7,
            "Bajaj Finance": 1.6,
            "Bharti Airtel": 1.5,
            "HDFC Bank": 1.3,
            "ICICI Bank": 1.1,
        },
    },
    -20: {
        "name": "Axis Small Cap Fund",
        "amc": "Axis",
        "category": "Small Cap",
        "month": "2026-05",
        "holdings": {
            "CCL Products": 3.1,
            "Brigade Enterprises": 2.8,
            "Galaxy Surfactants": 2.5,
            "TeamLease Services": 2.3,
            "Sapphire Foods": 2.1,
            "CMS Info Systems": 1.9,
            "EIH": 1.8,
            "Birlasoft": 1.7,
            "IIFL Finance": 1.6,
            "Chalet Hotels": 1.5,
            "Finolex Industries": 1.4,
            "Blue Star": 1.3,
            "Praj Industries": 1.2,
            "Cera Sanitaryware": 1.1,
            "SJS Enterprises": 1.0,
            "Quess Corp": 0.9,
            "Elgi Equipments": 0.8,
            "Ratnamani Metals": 0.7,
            "Lemon Tree Hotels": 0.6,
            "Mastek": 0.5,
        },
    },
    -10: {
        "name": "Bandhan Large Cap Fund",
        "amc": "Bandhan",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 10.1,
            "ICICI Bank": 8.3,
            "Reliance Industries": 7.0,
            "Infosys": 6.4,
            "TCS": 5.2,
            "Larsen & Toubro": 4.7,
            "ITC": 3.9,
            "Bharti Airtel": 3.5,
            "State Bank of India": 3.1,
            "Bajaj Finance": 2.8,
            "Axis Bank": 2.5,
            "Kotak Mahindra Bank": 2.3,
            "HCL Technologies": 2.1,
            "Hindustan Unilever": 1.8,
            "Maruti Suzuki": 1.7,
            "Sun Pharma": 1.5,
            "NTPC": 1.4,
            "Titan Company": 1.3,
            "Mahindra & Mahindra": 1.2,
            "Power Grid Corp": 1.1,
        },
    },
    -8: {
        "name": "Canara Robeco Bluechip Equity Fund",
        "amc": "Canara Robeco",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.0,
            "ICICI Bank": 7.5,
            "Infosys": 6.8,
            "Reliance Industries": 6.5,
            "TCS": 5.4,
            "Larsen & Toubro": 4.3,
            "Bharti Airtel": 3.7,
            "Bajaj Finance": 3.4,
            "ITC": 3.1,
            "State Bank of India": 2.8,
            "Axis Bank": 2.5,
            "Kotak Mahindra Bank": 2.3,
            "HCL Technologies": 2.1,
            "Hindustan Unilever": 1.9,
            "Maruti Suzuki": 1.7,
            "Sun Pharma": 1.6,
            "Titan Company": 1.5,
            "Asian Paints": 1.3,
            "Wipro": 1.2,
            "NTPC": 1.1,
        },
    },
    -17: {
        "name": "Canara Robeco Emerging Equities",
        "amc": "Canara Robeco",
        "category": "Mid Cap",
        "month": "2026-05",
        "holdings": {
            "Persistent Systems": 4.2,
            "Cholamandalam Inv": 3.8,
            "Federal Bank": 3.5,
            "Coforge": 3.2,
            "Trent": 3.0,
            "Indian Hotels": 2.8,
            "Supreme Industries": 2.6,
            "PI Industries": 2.4,
            "Sundaram Finance": 2.2,
            "APL Apollo Tubes": 2.0,
            "Page Industries": 1.9,
            "KPIT Technologies": 1.8,
            "Bharat Forge": 1.7,
            "Max Healthcare": 1.6,
            "HDFC Bank": 1.5,
            "ICICI Bank": 1.4,
            "Voltas": 1.3,
            "Astral": 1.2,
            "Blue Star": 1.1,
            "Crompton Greaves CE": 1.0,
        },
    },
    -28: {
        "name": "DSP Flexi Cap Fund",
        "amc": "DSP",
        "category": "Flexi Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 8.5,
            "ICICI Bank": 6.9,
            "Infosys": 5.8,
            "Reliance Industries": 5.2,
            "TCS": 4.5,
            "Larsen & Toubro": 4.0,
            "Bharti Airtel": 3.5,
            "State Bank of India": 3.1,
            "ITC": 2.8,
            "Bajaj Finance": 2.5,
            "Axis Bank": 2.3,
            "HCL Technologies": 2.1,
            "Kotak Mahindra Bank": 1.9,
            "Sun Pharma": 1.7,
            "Maruti Suzuki": 1.6,
            "Hindustan Unilever": 1.5,
            "NTPC": 1.4,
            "Titan Company": 1.3,
            "Mahindra & Mahindra": 1.2,
            "UltraTech Cement": 1.0,
        },
    },
    -12: {
        "name": "DSP Midcap Fund",
        "amc": "DSP",
        "category": "Mid Cap",
        "month": "2026-05",
        "holdings": {
            "Persistent Systems": 4.8,
            "Coforge": 4.2,
            "Cholamandalam Inv": 3.9,
            "Federal Bank": 3.5,
            "Supreme Industries": 3.2,
            "Indian Hotels": 3.0,
            "Trent": 2.8,
            "Sundaram Finance": 2.6,
            "PI Industries": 2.4,
            "APL Apollo Tubes": 2.2,
            "Mphasis": 2.1,
            "Page Industries": 2.0,
            "Astral": 1.9,
            "KPIT Technologies": 1.7,
            "Voltas": 1.6,
            "Schaeffler India": 1.5,
            "Max Healthcare": 1.4,
            "Bharat Forge": 1.3,
            "Dalmia Bharat": 1.2,
            "Crompton Greaves CE": 1.1,
        },
    },
    -52: {
        "name": "HDFC Balanced Advantage Fund",
        "amc": "HDFC",
        "category": "Balanced Advantage Fund",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 7.2,
            "HDFC Bank": 6.5,
            "Reliance Industries": 5.2,
            "ITC": 4.5,
            "Larsen & Toubro": 4.0,
            "Infosys": 3.5,
            "TCS": 3.1,
            "State Bank of India": 2.8,
            "Bharti Airtel": 2.5,
            "Axis Bank": 2.3,
            "NTPC": 2.1,
            "Coal India": 1.9,
            "Bajaj Finance": 1.7,
            "HCL Technologies": 1.5,
            "Kotak Mahindra Bank": 1.4,
            "Sun Pharma": 1.3,
            "Mahindra & Mahindra": 1.2,
            "Power Grid Corp": 1.1,
            "Maruti Suzuki": 1.0,
            "Hindustan Unilever": 0.9,
        },
    },
    -25: {
        "name": "HDFC Flexi Cap Fund",
        "amc": "HDFC",
        "category": "Flexi Cap",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 9.5,
            "HDFC Bank": 8.2,
            "Reliance Industries": 6.8,
            "Infosys": 5.5,
            "ITC": 5.0,
            "Larsen & Toubro": 4.5,
            "TCS": 4.0,
            "State Bank of India": 3.6,
            "Bharti Airtel": 3.2,
            "Axis Bank": 2.8,
            "Bajaj Finance": 2.5,
            "HCL Technologies": 2.2,
            "NTPC": 2.0,
            "Kotak Mahindra Bank": 1.8,
            "Sun Pharma": 1.6,
            "Hindustan Unilever": 1.5,
            "Maruti Suzuki": 1.4,
            "Titan Company": 1.3,
            "Mahindra & Mahindra": 1.2,
            "UltraTech Cement": 1.1,
        },
    },
    -46: {
        "name": "HDFC Index Fund Nifty 50 Plan",
        "amc": "HDFC",
        "category": "Index Funds",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 12.4,
            "Reliance Industries": 10.1,
            "ICICI Bank": 8.0,
            "Infosys": 6.2,
            "TCS": 4.7,
            "Larsen & Toubro": 4.1,
            "ITC": 3.9,
            "Bharti Airtel": 3.7,
            "State Bank of India": 3.4,
            "Axis Bank": 2.9,
            "Bajaj Finance": 2.6,
            "Kotak Mahindra Bank": 2.3,
            "HCL Technologies": 2.1,
            "Hindustan Unilever": 1.9,
            "Maruti Suzuki": 1.7,
            "Sun Pharma": 1.5,
            "Titan Company": 1.4,
            "NTPC": 1.3,
            "Asian Paints": 1.2,
            "Power Grid Corp": 1.1,
        },
    },
    -32: {
        "name": "HDFC Large and Mid Cap Fund",
        "amc": "HDFC",
        "category": "Large & Mid Cap",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 8.8,
            "HDFC Bank": 7.5,
            "Reliance Industries": 5.8,
            "Larsen & Toubro": 5.0,
            "Infosys": 4.5,
            "TCS": 3.9,
            "State Bank of India": 3.5,
            "ITC": 3.2,
            "Bharti Airtel": 2.9,
            "Axis Bank": 2.6,
            "Indian Hotels": 2.3,
            "Bajaj Finance": 2.1,
            "Persistent Systems": 1.9,
            "HCL Technologies": 1.8,
            "Cholamandalam Inv": 1.7,
            "Federal Bank": 1.6,
            "NTPC": 1.5,
            "Kotak Mahindra Bank": 1.4,
            "Sun Pharma": 1.3,
            "Mahindra & Mahindra": 1.2,
        },
    },
    -13: {
        "name": "HDFC Mid-Cap Opportunities Fund",
        "amc": "HDFC",
        "category": "Mid Cap",
        "month": "2026-05",
        "holdings": {
            "Indian Hotels": 4.5,
            "Persistent Systems": 4.0,
            "Cholamandalam Inv": 3.6,
            "Federal Bank": 3.3,
            "Coforge": 3.0,
            "Trent": 2.8,
            "Supreme Industries": 2.5,
            "Max Healthcare": 2.3,
            "Voltas": 2.1,
            "PI Industries": 2.0,
            "APL Apollo Tubes": 1.9,
            "Bharat Forge": 1.8,
            "Mphasis": 1.7,
            "Astral": 1.6,
            "Dalmia Bharat": 1.5,
            "Sundaram Finance": 1.4,
            "KPIT Technologies": 1.3,
            "Page Industries": 1.2,
            "Schaeffler India": 1.1,
            "Crompton Greaves CE": 1.0,
        },
    },
    -21: {
        "name": "HDFC Small Cap Fund",
        "amc": "HDFC",
        "category": "Small Cap",
        "month": "2026-05",
        "holdings": {
            "Firstsource Solutions": 3.0,
            "eClerx Services": 2.7,
            "Aarti Industries": 2.4,
            "Blue Star": 2.2,
            "Sonata Software": 2.0,
            "Bank of Baroda": 1.9,
            "Carborundum Universal": 1.8,
            "IIFL Finance": 1.7,
            "Bharat Forge": 1.6,
            "Finolex Industries": 1.5,
            "Crompton Greaves CE": 1.4,
            "EIH": 1.3,
            "Praj Industries": 1.2,
            "Elgi Equipments": 1.1,
            "Galaxy Surfactants": 1.0,
            "CMS Info Systems": 0.9,
            "Quess Corp": 0.8,
            "Ratnamani Metals": 0.7,
            "Cera Sanitaryware": 0.6,
            "Aether Industries": 0.5,
        },
    },
    -4: {
        "name": "HDFC Top 100 Fund",
        "amc": "HDFC",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 9.8,
            "HDFC Bank": 8.9,
            "Reliance Industries": 7.1,
            "Infosys": 6.2,
            "ITC": 5.5,
            "Larsen & Toubro": 5.0,
            "TCS": 4.5,
            "State Bank of India": 4.0,
            "Bharti Airtel": 3.7,
            "Axis Bank": 3.4,
            "NTPC": 3.1,
            "Bajaj Finance": 2.8,
            "HCL Technologies": 2.5,
            "Kotak Mahindra Bank": 2.2,
            "Sun Pharma": 2.0,
            "Hindustan Unilever": 1.9,
            "Power Grid Corp": 1.7,
            "Titan Company": 1.5,
            "Mahindra & Mahindra": 1.4,
            "UltraTech Cement": 1.2,
        },
    },
    -51: {
        "name": "ICICI Prudential Balanced Advantage Fund",
        "amc": "ICICI Prudential",
        "category": "Balanced Advantage Fund",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 6.8,
            "HDFC Bank": 5.9,
            "Reliance Industries": 5.0,
            "Infosys": 4.2,
            "TCS": 3.5,
            "Larsen & Toubro": 3.1,
            "State Bank of India": 2.8,
            "ITC": 2.5,
            "Bharti Airtel": 2.3,
            "Axis Bank": 2.1,
            "NTPC": 1.9,
            "Bajaj Finance": 1.8,
            "HCL Technologies": 1.6,
            "Kotak Mahindra Bank": 1.5,
            "Sun Pharma": 1.4,
            "Maruti Suzuki": 1.3,
            "Hindustan Unilever": 1.2,
            "Titan Company": 1.1,
            "Mahindra & Mahindra": 1.0,
            "Power Grid Corp": 0.9,
        },
    },
    -5: {
        "name": "ICICI Prudential Bluechip Fund",
        "amc": "ICICI Prudential",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.2,
            "ICICI Bank": 8.4,
            "Reliance Industries": 7.8,
            "Infosys": 6.1,
            "TCS": 5.3,
            "Larsen & Toubro": 4.8,
            "ITC": 4.2,
            "Bharti Airtel": 3.6,
            "State Bank of India": 3.3,
            "Axis Bank": 3.0,
            "Bajaj Finance": 2.7,
            "Maruti Suzuki": 2.5,
            "HCL Technologies": 2.3,
            "Sun Pharma": 2.1,
            "Kotak Mahindra Bank": 1.9,
            "Hindustan Unilever": 1.7,
            "NTPC": 1.5,
            "Titan Company": 1.4,
            "UltraTech Cement": 1.3,
            "Mahindra & Mahindra": 1.2,
        },
    },
    -57: {
        "name": "ICICI Prudential Infrastructure Fund",
        "amc": "ICICI Prudential",
        "category": "Sectoral/Thematic",
        "month": "2026-05",
        "holdings": {
            "Larsen & Toubro": 12.5,
            "NTPC": 8.8,
            "Power Grid Corp": 6.5,
            "Bharti Airtel": 5.8,
            "Adani Ports": 5.0,
            "NHPC": 4.2,
            "Siemens India": 3.8,
            "ABB India": 3.5,
            "Thermax": 3.0,
            "IRB Infrastructure": 2.6,
            "IRFC": 2.3,
            "HUDCO": 2.0,
            "Bharat Electronics": 1.8,
            "KEC International": 1.6,
            "Cummins India": 1.4,
            "Polycab India": 1.3,
            "CG Power & Ind": 1.2,
            "Kalpataru Projects": 1.1,
            "PNC Infratech": 1.0,
            "NCC": 0.9,
        },
    },
    -31: {
        "name": "ICICI Prudential Large & Mid Cap Fund",
        "amc": "ICICI Prudential",
        "category": "Large & Mid Cap",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 8.5,
            "HDFC Bank": 7.2,
            "Reliance Industries": 6.0,
            "Infosys": 5.1,
            "TCS": 4.3,
            "Larsen & Toubro": 3.9,
            "State Bank of India": 3.4,
            "Bharti Airtel": 3.1,
            "ITC": 2.8,
            "Axis Bank": 2.5,
            "Bajaj Finance": 2.3,
            "Persistent Systems": 2.1,
            "HCL Technologies": 1.9,
            "Kotak Mahindra Bank": 1.8,
            "Federal Bank": 1.7,
            "Cholamandalam Inv": 1.6,
            "Sun Pharma": 1.5,
            "Mahindra & Mahindra": 1.4,
            "Maruti Suzuki": 1.3,
            "NTPC": 1.2,
        },
    },
    -54: {
        "name": "ICICI Prudential Technology Fund",
        "amc": "ICICI Prudential",
        "category": "Sectoral/Thematic",
        "month": "2026-05",
        "holdings": {
            "Infosys": 19.2,
            "TCS": 15.8,
            "HCL Technologies": 10.5,
            "Wipro": 7.0,
            "Tech Mahindra": 6.2,
            "LTIMindtree": 4.8,
            "Persistent Systems": 4.0,
            "Coforge": 3.5,
            "Mphasis": 3.0,
            "KPIT Technologies": 2.5,
            "Cyient": 2.0,
            "Mastek": 1.5,
            "Tata Elxsi": 1.3,
            "Oracle Financial": 1.2,
            "Birlasoft": 1.1,
            "Zensar Technologies": 1.0,
            "Firstsource Solutions": 0.9,
            "eClerx Services": 0.8,
            "Sonata Software": 0.7,
        },
    },
    -33: {
        "name": "ICICI Prudential Value Discovery Fund",
        "amc": "ICICI Prudential",
        "category": "Value / Contra",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 7.5,
            "NTPC": 5.8,
            "ITC": 5.2,
            "State Bank of India": 4.8,
            "ONGC": 4.2,
            "Infosys": 3.9,
            "Larsen & Toubro": 3.5,
            "HDFC Bank": 3.3,
            "Sun Pharma": 3.0,
            "Bharti Airtel": 2.8,
            "TCS": 2.5,
            "Axis Bank": 2.3,
            "HCL Technologies": 2.1,
            "Power Grid Corp": 2.0,
            "Coal India": 1.8,
            "Hindustan Unilever": 1.6,
            "Maruti Suzuki": 1.5,
            "Bajaj Finance": 1.4,
            "Mahindra & Mahindra": 1.3,
            "Tech Mahindra": 1.2,
        },
    },
    -36: {
        "name": "Invesco India Contra Fund",
        "amc": "Invesco",
        "category": "Value / Contra",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 7.2,
            "ICICI Bank": 6.0,
            "Reliance Industries": 5.5,
            "Infosys": 4.8,
            "TCS": 4.2,
            "Larsen & Toubro": 3.8,
            "ITC": 3.4,
            "Bharti Airtel": 3.0,
            "State Bank of India": 2.7,
            "Bajaj Finance": 2.5,
            "HCL Technologies": 2.2,
            "NTPC": 2.0,
            "Axis Bank": 1.9,
            "Sun Pharma": 1.7,
            "Kotak Mahindra Bank": 1.6,
            "Titan Company": 1.5,
            "Mahindra & Mahindra": 1.4,
            "UltraTech Cement": 1.3,
            "Maruti Suzuki": 1.2,
            "Hindustan Unilever": 1.1,
        },
    },
    -26: {
        "name": "JM Flexicap Fund",
        "amc": "JM Financial",
        "category": "Flexi Cap",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 8.2,
            "HDFC Bank": 6.8,
            "Reliance Industries": 5.5,
            "Larsen & Toubro": 5.0,
            "State Bank of India": 4.3,
            "Infosys": 3.8,
            "ITC": 3.5,
            "NTPC": 3.2,
            "Bharti Airtel": 2.9,
            "Axis Bank": 2.6,
            "TCS": 2.4,
            "HCL Technologies": 2.1,
            "Mahindra & Mahindra": 2.0,
            "Coal India": 1.8,
            "Power Grid Corp": 1.6,
            "Bajaj Finance": 1.5,
            "Oil India": 1.4,
            "BPCL": 1.3,
            "Bharat Electronics": 1.2,
            "Titan Company": 1.1,
        },
    },
    -6: {
        "name": "Kotak Bluechip Fund",
        "amc": "Kotak Mahindra",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 9.1,
            "HDFC Bank": 8.7,
            "Reliance Industries": 7.4,
            "Infosys": 6.8,
            "TCS": 5.6,
            "Larsen & Toubro": 4.4,
            "Bharti Airtel": 3.8,
            "ITC": 3.5,
            "Bajaj Finance": 3.2,
            "State Bank of India": 3.0,
            "Axis Bank": 2.7,
            "Kotak Mahindra Bank": 2.4,
            "HCL Technologies": 2.2,
            "Hindustan Unilever": 2.0,
            "Maruti Suzuki": 1.8,
            "Sun Pharma": 1.6,
            "Titan Company": 1.5,
            "Asian Paints": 1.3,
            "NTPC": 1.2,
            "UltraTech Cement": 1.1,
        },
    },
    -14: {
        "name": "Kotak Emerging Equity Fund",
        "amc": "Kotak Mahindra",
        "category": "Mid Cap",
        "month": "2026-05",
        "holdings": {
            "Persistent Systems": 4.5,
            "Coforge": 4.0,
            "Cholamandalam Inv": 3.7,
            "Federal Bank": 3.3,
            "Trent": 3.0,
            "Supreme Industries": 2.8,
            "Indian Hotels": 2.6,
            "Sundaram Finance": 2.4,
            "Voltas": 2.2,
            "PI Industries": 2.0,
            "Max Healthcare": 1.9,
            "APL Apollo Tubes": 1.8,
            "Page Industries": 1.7,
            "Astral": 1.6,
            "Bharat Forge": 1.5,
            "Mphasis": 1.4,
            "KPIT Technologies": 1.3,
            "Schaeffler India": 1.2,
            "Dalmia Bharat": 1.1,
            "Crompton Greaves CE": 1.0,
        },
    },
    -22: {
        "name": "Kotak Small Cap Fund",
        "amc": "Kotak Mahindra",
        "category": "Small Cap",
        "month": "2026-05",
        "holdings": {
            "Blue Star": 3.3,
            "Cyient": 2.9,
            "Century Textiles": 2.6,
            "Kaynes Technology": 2.4,
            "CMS Info Systems": 2.2,
            "Finolex Industries": 2.0,
            "Cera Sanitaryware": 1.8,
            "EIH": 1.7,
            "IIFL Finance": 1.6,
            "Quess Corp": 1.5,
            "Praj Industries": 1.4,
            "Elgi Equipments": 1.3,
            "Galaxy Surfactants": 1.2,
            "SJS Enterprises": 1.1,
            "Ratnamani Metals": 1.0,
            "Mold-Tek Packaging": 0.9,
            "Lemon Tree Hotels": 0.8,
            "Aether Industries": 0.7,
            "Clean Science & Tech": 0.6,
            "Mastek": 0.5,
        },
    },
    -39: {
        "name": "Mirae Asset Focused Fund",
        "amc": "Mirae Asset",
        "category": "Focused Fund",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.8,
            "ICICI Bank": 8.2,
            "Reliance Industries": 7.0,
            "Infosys": 6.2,
            "TCS": 5.5,
            "Larsen & Toubro": 4.8,
            "Bharti Airtel": 4.2,
            "Bajaj Finance": 3.5,
            "State Bank of India": 3.0,
            "ITC": 2.7,
            "HCL Technologies": 2.4,
            "Kotak Mahindra Bank": 2.2,
            "Axis Bank": 2.0,
            "Titan Company": 1.8,
            "Sun Pharma": 1.6,
            "Hindustan Unilever": 1.5,
            "Maruti Suzuki": 1.4,
            "NTPC": 1.3,
            "UltraTech Cement": 1.2,
            "Power Grid Corp": 1.1,
        },
    },
    -29: {
        "name": "Mirae Asset Large & Midcap Fund",
        "amc": "Mirae Asset",
        "category": "Large & Mid Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 8.1,
            "ICICI Bank": 6.5,
            "Reliance Industries": 5.8,
            "Infosys": 4.9,
            "TCS": 4.2,
            "Larsen & Toubro": 3.8,
            "Bharti Airtel": 3.3,
            "Persistent Systems": 2.9,
            "State Bank of India": 2.7,
            "Cholamandalam Inv": 2.5,
            "ITC": 2.3,
            "Bajaj Finance": 2.1,
            "Federal Bank": 1.9,
            "Kotak Mahindra Bank": 1.8,
            "Coforge": 1.7,
            "HCL Technologies": 1.6,
            "Supreme Industries": 1.5,
            "Trent": 1.4,
            "Axis Bank": 1.3,
            "Sun Pharma": 1.2,
        },
    },
    -2: {
        "name": "Mirae Asset Large Cap Fund",
        "amc": "Mirae Asset",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 10.2,
            "ICICI Bank": 7.8,
            "Reliance Industries": 7.5,
            "Infosys": 6.9,
            "TCS": 5.5,
            "Larsen & Toubro": 4.5,
            "Bharti Airtel": 4.1,
            "Axis Bank": 3.8,
            "State Bank of India": 3.6,
            "ITC": 3.2,
            "Bajaj Finance": 3.0,
            "HCL Technologies": 2.7,
            "Kotak Mahindra Bank": 2.5,
            "Maruti Suzuki": 2.3,
            "Sun Pharma": 2.1,
            "Hindustan Unilever": 2.0,
            "Titan Company": 1.8,
            "NTPC": 1.6,
            "UltraTech Cement": 1.4,
            "Power Grid Corp": 1.2,
        },
    },
    -41: {
        "name": "Mirae Asset Tax Saver Fund",
        "amc": "Mirae Asset",
        "category": "ELSS",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.5,
            "ICICI Bank": 7.8,
            "Reliance Industries": 6.5,
            "Infosys": 5.8,
            "TCS": 5.0,
            "Larsen & Toubro": 4.3,
            "Bharti Airtel": 3.8,
            "Axis Bank": 3.2,
            "State Bank of India": 3.0,
            "ITC": 2.7,
            "Bajaj Finance": 2.5,
            "HCL Technologies": 2.2,
            "Kotak Mahindra Bank": 2.0,
            "Sun Pharma": 1.8,
            "Maruti Suzuki": 1.6,
            "Hindustan Unilever": 1.5,
            "Titan Company": 1.4,
            "NTPC": 1.3,
            "UltraTech Cement": 1.2,
            "Power Grid Corp": 1.0,
        },
    },
    -15: {
        "name": "Motilal Oswal Midcap Fund",
        "amc": "Motilal Oswal",
        "category": "Mid Cap",
        "month": "2026-05",
        "holdings": {
            "Kalyan Jewellers": 5.1,
            "Persistent Systems": 4.6,
            "Polycab India": 4.2,
            "Coforge": 3.8,
            "Max Healthcare": 3.4,
            "Jio Financial": 3.1,
            "Federal Bank": 2.8,
            "Tube Investments": 2.5,
            "Indian Hotels": 2.3,
            "PI Industries": 2.1,
            "KEI Industries": 1.9,
            "Supreme Industries": 1.8,
            "BSE Ltd": 1.7,
            "Cholamandalam Inv": 1.6,
            "Trent": 1.5,
            "Dixon Technologies": 1.4,
            "KPIT Technologies": 1.3,
            "Bharat Forge": 1.2,
            "Mphasis": 1.1,
            "Sundaram Finance": 1.0,
        },
    },
    -48: {
        "name": "Motilal Oswal Nifty 50 Index Fund",
        "amc": "Motilal Oswal",
        "category": "Index Funds",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 12.3,
            "Reliance Industries": 10.0,
            "ICICI Bank": 8.0,
            "Infosys": 6.2,
            "TCS": 4.7,
            "Larsen & Toubro": 4.1,
            "ITC": 3.9,
            "Bharti Airtel": 3.7,
            "State Bank of India": 3.3,
            "Axis Bank": 2.9,
            "Bajaj Finance": 2.5,
            "Kotak Mahindra Bank": 2.2,
            "HCL Technologies": 2.0,
            "Hindustan Unilever": 1.8,
            "Maruti Suzuki": 1.6,
            "Sun Pharma": 1.4,
            "Titan Company": 1.3,
            "NTPC": 1.2,
            "Asian Paints": 1.1,
            "Power Grid Corp": 1.0,
        },
    },
    -49: {
        "name": "Motilal Oswal Nifty Midcap 150 Index Fund",
        "amc": "Motilal Oswal",
        "category": "Index Funds",
        "month": "2026-05",
        "holdings": {
            "Persistent Systems": 2.5,
            "Indian Hotels": 2.3,
            "Suzlon Energy": 2.1,
            "Max Healthcare": 2.0,
            "Federal Bank": 1.9,
            "Dixon Technologies": 1.8,
            "Coforge": 1.7,
            "BSE Ltd": 1.6,
            "Polycab India": 1.5,
            "Tube Investments": 1.4,
            "Mphasis": 1.3,
            "APL Apollo Tubes": 1.2,
            "Bharat Forge": 1.1,
            "Supreme Industries": 1.0,
            "KPIT Technologies": 0.9,
            "KEI Industries": 0.8,
            "Sundaram Finance": 0.7,
            "CG Power & Ind": 0.7,
            "Voltas": 0.6,
            "Astral": 0.6,
        },
    },
    -7: {
        "name": "Nippon India Large Cap Fund",
        "amc": "Nippon India",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 8.8,
            "ICICI Bank": 7.9,
            "Reliance Industries": 7.2,
            "Infosys": 5.8,
            "TCS": 5.1,
            "ITC": 4.6,
            "Larsen & Toubro": 4.2,
            "Bharti Airtel": 3.8,
            "State Bank of India": 3.5,
            "Axis Bank": 3.1,
            "Bajaj Finance": 2.8,
            "HCL Technologies": 2.5,
            "NTPC": 2.2,
            "Kotak Mahindra Bank": 2.0,
            "Hindustan Unilever": 1.8,
            "Maruti Suzuki": 1.6,
            "Sun Pharma": 1.5,
            "Titan Company": 1.4,
            "Power Grid Corp": 1.3,
            "UltraTech Cement": 1.1,
        },
    },
    -56: {
        "name": "Nippon India Pharma Fund",
        "amc": "Nippon India",
        "category": "Sectoral/Thematic",
        "month": "2026-05",
        "holdings": {
            "Sun Pharma": 13.0,
            "Dr Reddy's Labs": 10.2,
            "Cipla": 8.8,
            "Divi's Laboratories": 6.5,
            "Apollo Hospitals": 5.8,
            "Lupin": 5.0,
            "Aurobindo Pharma": 4.2,
            "Torrent Pharma": 3.5,
            "Max Healthcare": 3.0,
            "Zydus Lifesciences": 2.6,
            "Laurus Labs": 2.2,
            "Biocon": 1.8,
            "Glenmark Pharma": 1.5,
            "Alkem Laboratories": 1.3,
            "JB Chemicals": 1.2,
            "Ipca Laboratories": 1.1,
            "Fortis Healthcare": 1.0,
            "Natco Pharma": 0.9,
            "Syngene International": 0.8,
        },
    },
    -19: {
        "name": "Nippon India Small Cap Fund",
        "amc": "Nippon India",
        "category": "Small Cap",
        "month": "2026-05",
        "holdings": {
            "KPIT Technologies": 2.8,
            "Tube Investments": 2.5,
            "Carborundum Universal": 2.2,
            "Blue Star": 2.0,
            "Bharat Forge": 1.9,
            "Crompton Greaves CE": 1.8,
            "IIFL Finance": 1.7,
            "Finolex Industries": 1.6,
            "Ratnamani Metals": 1.5,
            "EIH": 1.4,
            "Praj Industries": 1.3,
            "Elgi Equipments": 1.2,
            "Galaxy Surfactants": 1.1,
            "CMS Info Systems": 1.0,
            "Aether Industries": 0.9,
            "Lemon Tree Hotels": 0.8,
            "SJS Enterprises": 0.7,
            "Clean Science & Tech": 0.7,
            "Quess Corp": 0.6,
            "Cera Sanitaryware": 0.6,
        },
    },
    -35: {
        "name": "Nippon India Value Fund",
        "amc": "Nippon India",
        "category": "Value / Contra",
        "month": "2026-05",
        "holdings": {
            "ICICI Bank": 7.0,
            "HDFC Bank": 6.2,
            "Reliance Industries": 5.5,
            "State Bank of India": 4.8,
            "ITC": 4.2,
            "Larsen & Toubro": 3.8,
            "NTPC": 3.4,
            "Infosys": 3.0,
            "Bharti Airtel": 2.7,
            "TCS": 2.4,
            "Coal India": 2.2,
            "Axis Bank": 2.0,
            "Power Grid Corp": 1.9,
            "Sun Pharma": 1.7,
            "HCL Technologies": 1.6,
            "Mahindra & Mahindra": 1.5,
            "ONGC": 1.4,
            "Bajaj Finance": 1.3,
            "Maruti Suzuki": 1.2,
            "Hindustan Unilever": 1.1,
        },
    },
    -16: {
        "name": "PGIM India Midcap Opportunities Fund",
        "amc": "PGIM India",
        "category": "Mid Cap",
        "month": "2026-05",
        "holdings": {
            "Persistent Systems": 5.5,
            "Indian Hotels": 4.1,
            "Cholamandalam Inv": 3.7,
            "Max Healthcare": 3.4,
            "Coforge": 3.1,
            "PI Industries": 2.8,
            "Federal Bank": 2.6,
            "APL Apollo Tubes": 2.3,
            "Supreme Industries": 2.1,
            "Bharat Forge": 1.9,
            "Trent": 1.8,
            "Dixon Technologies": 1.7,
            "Mphasis": 1.6,
            "Sundaram Finance": 1.5,
            "Astral": 1.4,
            "KPIT Technologies": 1.3,
            "Page Industries": 1.2,
            "Schaeffler India": 1.1,
            "Voltas": 1.0,
            "Crompton Greaves CE": 0.9,
        },
    },
    -24: {
        "name": "Parag Parikh Flexi Cap Fund",
        "amc": "PPFAS",
        "category": "Flexi Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 7.5,
            "ICICI Bank": 5.2,
            "ITC": 4.8,
            "Bajaj Holdings": 4.5,
            "Power Grid Corp": 4.1,
            "Coal India": 3.8,
            "HCL Technologies": 3.5,
            "Bharti Airtel": 3.2,
            "Maruti Suzuki": 2.9,
            "Axis Bank": 2.6,
            "NTPC": 2.4,
            "Wipro": 2.2,
            "Infosys": 2.0,
            "Reliance Industries": 1.8,
            "TCS": 1.6,
            "Balkrishna Industries": 1.5,
            "Zydus Lifesciences": 1.4,
            "Oracle Financial": 1.3,
            "Mahindra & Mahindra": 1.2,
            "Motilal Oswal Fin": 1.1,
        },
    },
    -27: {
        "name": "Quant Flexi Cap Fund",
        "amc": "Quant",
        "category": "Flexi Cap",
        "month": "2026-05",
        "holdings": {
            "Reliance Industries": 8.5,
            "HDFC Bank": 5.8,
            "Jio Financial": 4.5,
            "Adani Ports": 3.8,
            "ITC": 3.5,
            "IRB Infrastructure": 3.2,
            "State Bank of India": 2.9,
            "Aurobindo Pharma": 2.6,
            "Larsen & Toubro": 2.4,
            "NTPC": 2.2,
            "Bharti Airtel": 2.0,
            "Laurus Labs": 1.8,
            "Steel Authority": 1.6,
            "ONGC": 1.5,
            "Bikaji Foods": 1.4,
            "Bajaj Finance": 1.3,
            "IRFC": 1.2,
            "Infosys": 1.1,
            "Bharat Electronics": 1.0,
            "Chambal Fertilisers": 0.9,
        },
    },
    -58: {
        "name": "Quant Infrastructure Fund",
        "amc": "Quant",
        "category": "Sectoral/Thematic",
        "month": "2026-05",
        "holdings": {
            "Reliance Industries": 8.0,
            "Larsen & Toubro": 6.5,
            "Adani Ports": 5.2,
            "IRB Infrastructure": 4.5,
            "NTPC": 4.0,
            "IRFC": 3.5,
            "Siemens India": 3.0,
            "Power Grid Corp": 2.7,
            "NHPC": 2.4,
            "Jio Financial": 2.2,
            "Bharat Electronics": 2.0,
            "ABB India": 1.8,
            "HUDCO": 1.6,
            "Steel Authority": 1.5,
            "Bharti Airtel": 1.4,
            "CG Power & Ind": 1.3,
            "Coal India": 1.2,
            "NCC": 1.1,
            "KEC International": 1.0,
            "Thermax": 0.9,
        },
    },
    -23: {
        "name": "Quant Small Cap Fund",
        "amc": "Quant",
        "category": "Small Cap",
        "month": "2026-05",
        "holdings": {
            "Reliance Industries": 5.8,
            "IRB Infrastructure": 4.2,
            "Jio Financial": 3.5,
            "Bikaji Foods": 3.1,
            "ONGC": 2.8,
            "Steel Authority": 2.5,
            "Laurus Labs": 2.2,
            "IRFC": 2.0,
            "Hinduja Global": 1.8,
            "Jubilant FoodWorks": 1.6,
            "Aurobindo Pharma": 1.5,
            "Chambal Fertilisers": 1.4,
            "GNFC": 1.3,
            "IEX": 1.2,
            "Cyient": 1.1,
            "Blue Star": 1.0,
            "Canara Bank": 0.9,
            "Motilal Oswal Fin": 0.8,
            "Bharat Electronics": 0.7,
            "HUDCO": 0.6,
        },
    },
    -42: {
        "name": "Quant Tax Plan",
        "amc": "Quant",
        "category": "ELSS",
        "month": "2026-05",
        "holdings": {
            "Reliance Industries": 7.8,
            "HDFC Bank": 5.2,
            "Jio Financial": 4.0,
            "ITC": 3.5,
            "Adani Ports": 3.2,
            "State Bank of India": 2.9,
            "IRB Infrastructure": 2.6,
            "NTPC": 2.4,
            "Aurobindo Pharma": 2.2,
            "Larsen & Toubro": 2.0,
            "Steel Authority": 1.8,
            "Bharti Airtel": 1.7,
            "Bikaji Foods": 1.5,
            "ONGC": 1.4,
            "Laurus Labs": 1.3,
            "Infosys": 1.2,
            "IRFC": 1.1,
            "Bharat Electronics": 1.0,
            "Chambal Fertilisers": 0.9,
            "Coal India": 0.8,
        },
    },
    -3: {
        "name": "SBI Bluechip Fund",
        "amc": "SBI",
        "category": "Large Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 9.5,
            "ICICI Bank": 8.1,
            "Reliance Industries": 7.3,
            "Infosys": 6.5,
            "TCS": 5.8,
            "Larsen & Toubro": 4.6,
            "Bharti Airtel": 3.9,
            "Bajaj Finance": 3.5,
            "ITC": 3.3,
            "Kotak Mahindra Bank": 3.0,
            "State Bank of India": 2.8,
            "HCL Technologies": 2.5,
            "Axis Bank": 2.3,
            "Hindustan Unilever": 2.1,
            "Maruti Suzuki": 2.0,
            "Sun Pharma": 1.9,
            "Titan Company": 1.7,
            "Asian Paints": 1.5,
            "NTPC": 1.3,
            "UltraTech Cement": 1.2,
        },
    },
    -34: {
        "name": "SBI Contra Fund",
        "amc": "SBI",
        "category": "Value / Contra",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 6.8,
            "ICICI Bank": 5.5,
            "ITC": 5.0,
            "Reliance Industries": 4.5,
            "State Bank of India": 4.0,
            "Larsen & Toubro": 3.6,
            "NTPC": 3.2,
            "Coal India": 2.8,
            "Infosys": 2.5,
            "Axis Bank": 2.3,
            "TCS": 2.1,
            "ONGC": 2.0,
            "Power Grid Corp": 1.8,
            "Bharti Airtel": 1.7,
            "HCL Technologies": 1.6,
            "Mahindra & Mahindra": 1.5,
            "BPCL": 1.4,
            "Sun Pharma": 1.3,
            "GAIL India": 1.2,
            "Bharat Electronics": 1.1,
        },
    },
    -50: {
        "name": "SBI Equity Hybrid Fund",
        "amc": "SBI",
        "category": "Aggressive Hybrid Fund",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 7.2,
            "ICICI Bank": 6.1,
            "Infosys": 4.8,
            "Reliance Industries": 4.5,
            "TCS": 3.8,
            "Larsen & Toubro": 3.3,
            "Bharti Airtel": 2.9,
            "ITC": 2.7,
            "State Bank of India": 2.5,
            "Bajaj Finance": 2.3,
            "Axis Bank": 2.1,
            "Kotak Mahindra Bank": 1.9,
            "HCL Technologies": 1.7,
            "Hindustan Unilever": 1.5,
            "Sun Pharma": 1.4,
            "Titan Company": 1.3,
            "Maruti Suzuki": 1.2,
            "NTPC": 1.1,
            "Asian Paints": 1.0,
            "Mahindra & Mahindra": 0.9,
        },
    },
    -38: {
        "name": "SBI Focused Equity Fund",
        "amc": "SBI",
        "category": "Focused Fund",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 8.8,
            "ICICI Bank": 7.5,
            "Reliance Industries": 6.5,
            "Infosys": 5.8,
            "TCS": 5.0,
            "Larsen & Toubro": 4.5,
            "Bharti Airtel": 4.0,
            "State Bank of India": 3.5,
            "Bajaj Finance": 3.2,
            "ITC": 2.8,
            "HCL Technologies": 2.5,
            "Kotak Mahindra Bank": 2.3,
            "Axis Bank": 2.1,
            "Sun Pharma": 1.9,
            "Titan Company": 1.7,
            "Hindustan Unilever": 1.6,
            "Maruti Suzuki": 1.5,
            "NTPC": 1.4,
            "Asian Paints": 1.3,
            "Mahindra & Mahindra": 1.2,
        },
    },
    -55: {
        "name": "SBI Healthcare Opportunities Fund",
        "amc": "SBI",
        "category": "Sectoral/Thematic",
        "month": "2026-05",
        "holdings": {
            "Sun Pharma": 12.5,
            "Dr Reddy's Labs": 9.8,
            "Cipla": 8.5,
            "Divi's Laboratories": 7.2,
            "Apollo Hospitals": 6.5,
            "Max Healthcare": 5.8,
            "Aurobindo Pharma": 4.5,
            "Torrent Pharma": 3.8,
            "Lupin": 3.2,
            "Zydus Lifesciences": 2.8,
            "Laurus Labs": 2.4,
            "Alkem Laboratories": 2.1,
            "Biocon": 1.9,
            "Glenmark Pharma": 1.6,
            "Ipca Laboratories": 1.4,
            "JB Chemicals": 1.2,
            "Fortis Healthcare": 1.1,
            "Narayana Hrudayalaya": 1.0,
            "Syngene International": 0.9,
            "Natco Pharma": 0.8,
        },
    },
    -30: {
        "name": "SBI Large & Midcap Fund",
        "amc": "SBI",
        "category": "Large & Mid Cap",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 7.8,
            "ICICI Bank": 6.2,
            "Reliance Industries": 5.5,
            "Infosys": 4.8,
            "TCS": 4.1,
            "Larsen & Toubro": 3.7,
            "Bharti Airtel": 3.2,
            "State Bank of India": 2.9,
            "ITC": 2.7,
            "Bajaj Finance": 2.4,
            "Cholamandalam Inv": 2.2,
            "Federal Bank": 2.0,
            "Kotak Mahindra Bank": 1.9,
            "Persistent Systems": 1.8,
            "HCL Technologies": 1.7,
            "Axis Bank": 1.6,
            "Indian Hotels": 1.5,
            "Sun Pharma": 1.4,
            "Maruti Suzuki": 1.3,
            "Trent": 1.2,
        },
    },
    -43: {
        "name": "SBI Long Term Equity Fund",
        "amc": "SBI",
        "category": "ELSS",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 8.2,
            "ICICI Bank": 6.8,
            "Reliance Industries": 5.8,
            "Infosys": 5.2,
            "TCS": 4.5,
            "Larsen & Toubro": 4.0,
            "Bharti Airtel": 3.5,
            "State Bank of India": 3.1,
            "ITC": 2.8,
            "Bajaj Finance": 2.5,
            "Axis Bank": 2.3,
            "HCL Technologies": 2.1,
            "Kotak Mahindra Bank": 1.9,
            "Sun Pharma": 1.7,
            "Maruti Suzuki": 1.5,
            "Hindustan Unilever": 1.4,
            "Titan Company": 1.3,
            "NTPC": 1.2,
            "Mahindra & Mahindra": 1.1,
            "UltraTech Cement": 1.0,
        },
    },
    -18: {
        "name": "SBI Small Cap Fund",
        "amc": "SBI",
        "category": "Small Cap",
        "month": "2026-05",
        "holdings": {
            "IIFL Finance": 3.2,
            "Chalet Hotels": 2.9,
            "Finolex Industries": 2.7,
            "Blue Star": 2.5,
            "Ratnamani Metals": 2.4,
            "IIFL Wealth Mgmt": 2.3,
            "Elgi Equipments": 2.1,
            "Cera Sanitaryware": 2.0,
            "EIH": 1.9,
            "CMS Info Systems": 1.8,
            "Mold-Tek Packaging": 1.7,
            "Karur Vysya Bank": 1.6,
            "Quess Corp": 1.5,
            "KPIT Technologies": 1.4,
            "SJS Enterprises": 1.3,
            "Aether Industries": 1.2,
            "Praj Industries": 1.1,
            "Galaxy Surfactants": 1.0,
            "Clean Science & Tech": 0.9,
            "Lemon Tree Hotels": 0.8,
        },
    },
    -53: {
        "name": "Tata Digital India Fund",
        "amc": "Tata",
        "category": "Sectoral/Thematic",
        "month": "2026-05",
        "holdings": {
            "Infosys": 18.5,
            "TCS": 16.2,
            "HCL Technologies": 9.8,
            "Wipro": 6.5,
            "Tech Mahindra": 5.8,
            "LTIMindtree": 5.2,
            "Persistent Systems": 4.5,
            "Coforge": 3.8,
            "Mphasis": 3.5,
            "KPIT Technologies": 3.2,
            "Cyient": 2.5,
            "Birlasoft": 2.2,
            "Zensar Technologies": 2.0,
            "Oracle Financial": 1.8,
            "Mastek": 1.5,
            "Tata Elxsi": 1.2,
            "Firstsource Solutions": 1.0,
            "Sonata Software": 0.9,
            "eClerx Services": 0.8,
        },
    },
    -45: {
        "name": "UTI Nifty 50 Index Fund",
        "amc": "UTI",
        "category": "Index Funds",
        "month": "2026-05",
        "holdings": {
            "HDFC Bank": 12.5,
            "Reliance Industries": 10.2,
            "ICICI Bank": 8.1,
            "Infosys": 6.3,
            "TCS": 4.8,
            "Larsen & Toubro": 4.2,
            "ITC": 4.0,
            "Bharti Airtel": 3.8,
            "State Bank of India": 3.4,
            "Axis Bank": 3.0,
            "Bajaj Finance": 2.6,
            "Kotak Mahindra Bank": 2.3,
            "HCL Technologies": 2.1,
            "Hindustan Unilever": 1.9,
            "Maruti Suzuki": 1.7,
            "Sun Pharma": 1.5,
            "Titan Company": 1.4,
            "NTPC": 1.3,
            "Asian Paints": 1.2,
            "Power Grid Corp": 1.1,
        },
    },
    -47: {
        "name": "UTI Nifty Next 50 Index Fund",
        "amc": "UTI",
        "category": "Index Funds",
        "month": "2026-05",
        "holdings": {
            "Adani Enterprises": 4.8,
            "Zomato": 4.5,
            "Jio Financial": 4.2,
            "Vedanta": 3.8,
            "Trent": 3.5,
            "Indian Oil Corp": 3.2,
            "BPCL": 3.0,
            "Siemens India": 2.8,
            "Pidilite Industries": 2.6,
            "Cholamandalam Inv": 2.4,
            "GAIL India": 2.2,
            "DLF": 2.0,
            "Godrej Consumer": 1.9,
            "Shriram Finance": 1.8,
            "Dabur India": 1.7,
            "Ambuja Cements": 1.6,
            "Havells India": 1.5,
            "Info Edge India": 1.4,
            "ABB India": 1.3,
            "Jindal Steel & Power": 1.2,
        },
    },
}
