"""
snapshot.py — 69 funds scraped from Groww.in
Generated: 2026-05-31
"""

SNAPSHOT_DATE = "May 2026"

SNAPSHOT_SCHEMES = {
    -1: {
        "family_id": -1, "name": "Quantum Value",
        "category": "Value", "amc": "Quant Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 83.91,
            "5 years": 27.03,
            "Category average (Equity Value Oriented)": 14.7,
            "Rank (Equity Value Oriented)": 14.0,
            "Fund returns": 13.2,
            "HDFC Bank Ltd.": 7.45,
            "ICICI Bank Ltd.": 6.62,
            "3 years": 6.28,
            "Tata Consultancy Services Ltd.": 5.0,
            "Infosys Ltd.": 4.5,
            "Kotak Mahindra Bank Ltd.": 3.92,
            "Crompton Greaves Consumer Electricals Ltd.": 3.58,
            "Aditya Birla Sun Life AMC Ltd.": 3.44,
            "Axis Bank Ltd.": 3.39,
            "ICICI Prudential Life Insurance Company Ltd.": 3.38,
            "Container Corporation Of India Ltd.": 3.33,
            "Star Health and Allied Insurance Company Ltd.": 3.18,
            "Exide Industries Ltd.": 3.13,
            "Bharti Airtel Ltd.": 3.13,
            "Wipro Ltd.": 3.1,
            "Tech Mahindra Ltd.": 3.1,
            "Hero Motocorp Ltd.": 2.98,
            "LIC Housing Finance Ltd.": 2.71,
            "State Bank of India": 2.66,
            "Cipla Ltd.": 2.61,
        },
    },
    -2: {
        "family_id": -2, "name": "Quantum ELSS Tax Saver",
        "category": "ELSS", "amc": "Quant Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 84.96,
            "5 years": 27.45,
            "Rank (Equity ELSS)": 27.0,
            "Fund returns": 15.5,
            "Category average (Equity ELSS)": 14.0,
            "HDFC Bank Ltd.": 7.37,
            "ICICI Bank Ltd.": 6.64,
            "3 years": 6.54,
            "Tata Consultancy Services Ltd.": 5.03,
            "Infosys Ltd.": 4.46,
            "Kotak Mahindra Bank Ltd.": 4.07,
            "Crompton Greaves Consumer Electricals Ltd.": 3.67,
            "Aditya Birla Sun Life AMC Ltd.": 3.6,
            "Axis Bank Ltd.": 3.38,
            "Container Corporation Of India Ltd.": 3.31,
            "ICICI Prudential Life Insurance Company Ltd.": 3.29,
            "Star Health and Allied Insurance Company Ltd.": 3.16,
            "Bharti Airtel Ltd.": 3.12,
            "Exide Industries Ltd.": 3.1,
            "Hero Motocorp Ltd.": 3.05,
            "Wipro Ltd.": 2.99,
            "State Bank of India": 2.99,
            "Tech Mahindra Ltd.": 2.92,
            "Cipla Ltd.": 2.74,
            "Nuvoco Vistas Corporation Ltd.": 2.67,
        },
    },
    -3: {
        "family_id": -3, "name": "Canara Robeco Infrastructure",
        "category": "Sectoral", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 68.75,
            "3 years": 26.16,
            "Fund returns": 17.2,
            "Category average (Equity Sectoral)": 15.4,
            "Rank (Equity Sectoral)": 11.0,
            "Larsen & Toubro Ltd": 9.45,
            "1 year": 5.86,
            "Reliance Industries Ltd": 4.54,
            "Repo": 4.38,
            "CG Power & Industrial Solutions Ltd": 4.32,
            "NTPC Ltd": 4.31,
            "State Bank of India": 4.18,
            "Tata Power Company Ltd": 3.91,
            "Bharat Electronics Ltd": 3.79,
            "Cummins India Ltd": 3.12,
            "Bharti Airtel Ltd": 3.08,
            "Power Grid Corporation of India Ltd": 3.0,
            "Power Finance Corporation Ltd": 2.99,
            "Ultratech Cement Ltd": 2.91,
            "GE T&D India Ltd": 2.83,
            "Interglobe Aviation Ltd": 2.78,
            "Hitachi Energy India Ltd": 2.75,
            "Solar Industries India Ltd": 2.59,
            "Dixon Technologies (India) Ltd": 2.31,
            "Hindalco Industries Ltd": 2.0,
        },
    },
    -4: {
        "family_id": -4, "name": "Canara Robeco Large Cap",
        "category": "Large Cap", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 24.91,
            "Fund returns": 13.9,
            "Category average (Equity Large Cap)": 13.2,
            "HDFC Bank Ltd": 8.33,
            "ICICI Bank Ltd": 7.71,
            "3 years": 6.81,
            "Reliance Industries Ltd": 5.54,
            "Bharti Airtel Ltd": 4.67,
            "State Bank of India": 4.5,
            "Larsen & Toubro Ltd": 4.23,
            "Infosys Ltd": 3.78,
            "Repo": 3.54,
            "Axis Bank Ltd": 3.29,
            "Mahindra & Mahindra Ltd": 3.04,
            "Bajaj Finance Ltd": 2.99,
            "Ultratech Cement Ltd": 2.45,
            "Kotak Mahindra Bank Ltd": 2.23,
            "Rank (Equity Large Cap)": 2.0,
            "Zomato Ltd": 1.99,
            "Sun Pharmaceutical Industries Ltd": 1.61,
            "Varun Beverages Ltd": 1.56,
            "Tech Mahindra Ltd": 1.5,
            "Tata Consumer Products Ltd": 1.45,
            "ITC Ltd": 1.43,
            "Maruti Suzuki India Ltd": 1.41,
        },
    },
    -5: {
        "family_id": -5, "name": "Canara Robeco Consumption",
        "category": "Thematic", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 27.57,
            "Fund returns": 15.8,
            "Category average (Equity Thematic)": 14.5,
            "Bharti Airtel Ltd.": 6.15,
            "3 years": 5.69,
            "HDFC Bank Ltd.": 5.17,
            "Eternal Ltd.": 4.55,
            "Maruti Suzuki India Ltd.": 4.52,
            "Mahindra & Mahindra Ltd.": 4.45,
            "ITC Ltd.": 4.31,
            "Britannia Industries Ltd.": 4.17,
            "Bajaj Finance Ltd.": 4.09,
            "Varun Beverages Ltd.": 3.51,
            "Rank (Equity Thematic)": 3.0,
            "Titan Company Ltd.": 2.84,
            "Godrej Consumer Products Ltd.": 2.8,
            "ICICI Bank Ltd.": 2.62,
            "Samvardhana Motherson International Ltd.": 2.57,
            "BSE Ltd.": 2.36,
            "Trent Ltd.": 2.29,
            "United Spirits Ltd.": 2.16,
            "Bajaj Auto Ltd.": 2.05,
            "FSN E-Commerce Ventures Ltd.": 2.02,
            "Jubilant FoodWorks Ltd.": 1.96,
            "Asian Paints Ltd.": 1.93,
        },
    },
    -6: {
        "family_id": -6, "name": "Canara Robeco Large and Mid Cap",
        "category": "Large & MidCap", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 28.91,
            "Fund returns": 18.8,
            "Category average (Equity Large & MidCap)": 14.7,
            "3 years": 9.0,
            "ICICI Bank Ltd.": 6.01,
            "Rank (Equity Large & MidCap)": 6.0,
            "The Indian Hotels Company Ltd.": 5.01,
            "TVS Motor Company Ltd.": 3.29,
            "Eternal Ltd.": 3.05,
            "The Federal Bank Ltd.": 3.01,
            "Bharat Electronics Ltd.": 2.91,
            "Mahindra & Mahindra Ltd.": 2.74,
            "UNO Minda Ltd.": 2.61,
            "Trent Ltd.": 2.5,
            "Bharti Airtel Ltd.": 2.4,
            "KPIT Technologies Ltd.": 2.28,
            "Dixon Technologies (India) Ltd.": 2.09,
            "Multi Commodity Exchange Of India Ltd.": 2.09,
            "PB Fintech Ltd.": 1.99,
            "Torrent Power Ltd.": 1.91,
            "HDFC Bank Ltd.": 1.89,
            "Tata Power Company Ltd.": 1.87,
            "Bajaj Finance Ltd.": 1.79,
            "Cholamandalam Investment and Finance Company Ltd.": 1.74,
            "Max Healthcare Institute Ltd.": 1.73,
        },
    },
    -7: {
        "family_id": -7, "name": "Canara Robeco ELSS Tax Saver",
        "category": "ELSS", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 29.42,
            "Fund returns": 14.9,
            "Category average (Equity ELSS)": 14.0,
            "3 years": 10.17,
            "Rank (Equity ELSS)": 8.0,
            "HDFC Bank Ltd.": 6.49,
            "ICICI Bank Ltd.": 6.43,
            "Reliance Industries Ltd.": 4.24,
            "State Bank of India": 3.7,
            "Larsen & Toubro Ltd.": 3.5,
            "Bharti Airtel Ltd.": 3.29,
            "Infosys Ltd.": 3.09,
            "Axis Bank Ltd.": 2.8,
            "Bajaj Finance Ltd.": 2.56,
            "GE Vernova T&D India Ltd": 2.06,
            "Divi's Laboratories Ltd.": 1.91,
            "Ultratech Cement Ltd.": 1.74,
            "Samvardhana Motherson International Ltd.": 1.7,
            "Eternal Ltd.": 1.69,
            "BSE Ltd.": 1.62,
            "CG Power and Industrial Solutions Ltd.": 1.62,
            "Interglobe Aviation Ltd.": 1.43,
            "NTPC Ltd.": 1.43,
            "TVS Motor Company Ltd.": 1.39,
            "JB Chemicals & Pharmaceuticals Ltd.": 1.38,
        },
    },
    -8: {
        "family_id": -8, "name": "Canara Robeco Income from Debt Instruments & Gold",
        "category": "Balanced Advantage", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "GOI": 26.36,
            "Category average (Hybrid Balanced Advantage)": 16.1,
            "Canara Robeco Gold Exchange Traded Fund": 11.41,
            "Maharashtra State": 4.9,
            "Reliance ETF Gold BeES": 4.8,
            "Fund returns": 4.3,
            "Power Finance Corpn. Ltd.": 3.99,
        },
    },
    -9: {
        "family_id": -9, "name": "Canara Robeco Short Term",
        "category": "Index", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "GOI": 12.27,
            "GOI": 9.65,
            "Housing Development Finance Corpn. Ltd.": 9.5,
            "Power Finance Corpn. Ltd.": 9.47,
            "Export-Import Bank Of India": 9.47,
            "Sundaram Finance Ltd.": 9.43,
            "Fund returns": 7.8,
            "Category average (Debt Short Duration)": 5.9,
            "Dewan Housing Finance Corpn. Ltd.": 4.76,
            "Power Grid Corporation of India Ltd.": 4.76,
            "LIC Housing Finance Ltd.": 4.75,
            "National Bank For Agriculture & Rural Development": 4.75,
            "National Thermal Power Corp. Ltd.": 4.74,
            "National Thermal Power Corp. Ltd.": 4.74,
            "Reserve Bank of India": 4.49,
            "Indiabulls Housing Finance Ltd.": 1.91,
        },
    },
    -10: {
        "family_id": -10, "name": "IDBI India Top 100 Equity",
        "category": "Large Cap", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Fund returns": 14.1,
            "Rank (Equity Large Cap)": 14.0,
            "Category average (Equity Large Cap)": 13.2,
            "HDFC Bank Ltd.": 7.98,
            "ICICI Bank Ltd.": 7.27,
            "Reliance Industries Ltd.": 6.46,
            "State Bank of India": 4.96,
            "Axis Bank Ltd.": 4.93,
            "Infosys Ltd.": 4.28,
            "Housing Development Finance Corporation Ltd.": 3.9,
            "Larsen & Toubro Ltd.": 2.92,
            "Tata Consultancy Services Ltd.": 2.69,
            "Kotak Mahindra Bank Ltd.": 2.29,
            "ABB India Ltd.": 2.25,
            "Ultratech Cement Ltd.": 2.16,
            "HCL Technologies Ltd.": 2.11,
            "Bajaj Finance Ltd.": 2.05,
            "Mahindra & Mahindra Ltd.": 2.01,
            "Persistent Systems Ltd.": 1.95,
            "Titan Company Ltd.": 1.89,
            "DLF Ltd.": 1.81,
            "Maruti Suzuki India Ltd.": 1.74,
            "ITC Ltd.": 1.69,
            "Tata Steel Ltd.": 1.58,
            "Sun Pharmaceutical Industries Ltd.": 1.56,
        },
    },
    -11: {
        "family_id": -11, "name": "IDBI Short Term Bond",
        "category": "Index", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Reserve Bank of India": 55.07,
            "Rank (Debt Short Duration)": 12.0,
            "State Bank of India": 11.56,
            "REC Ltd.": 10.16,
            "GOI": 9.76,
            "Fund returns": 7.7,
            "Category average (Debt Short Duration)": 6.6,
        },
    },
    -12: {
        "family_id": -12, "name": "IDFC Money Manager Investment",
        "category": "Index", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Fund returns": 7.9,
            "GOI": 7.4,
            "GOI": 6.49,
            "Category average (Debt Short Duration)": 5.9,
            "Power Finance Corpn. Ltd.": 5.35,
            "Housing Development Finance Corpn. Ltd.": 4.03,
            "LIC Housing Finance Ltd.": 3.66,
            "REC Ltd.": 3.55,
            "Indusind Bank Ltd.": 3.55,
            "Housing Development Finance Corpn. Ltd.": 2.93,
            "Housing Development Finance Corpn. Ltd.": 2.93,
            "LIC Housing Finance Ltd.": 2.9,
            "Cholamandalam Investment & Finance Co. Ltd.": 2.89,
            "National Bank For Agriculture & Rural Development": 2.86,
            "REC Ltd.": 2.84,
            "LIC Housing Finance Ltd.": 2.57,
            "HDB Financial Services Ltd.": 2.55,
            "LIC Housing Finance Ltd.": 2.17,
            "Tamilnadu State": 1.85,
            "Power Finance Corpn. Ltd.": 1.83,
            "Power Finance Corpn. Ltd.": 1.83,
            "Reliance Jio Infocomm Ltd.": 1.82,
            "Kotak Mahindra Prime Ltd.": 1.81,
            "Housing Development Finance Corpn. Ltd.": 1.81,
            "Kotak Mahindra Prime Ltd.": 1.8,
        },
    },
    -13: {
        "family_id": -13, "name": "Bandhan Focused",
        "category": "Flexi Cap", "amc": "Bandhan Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 38.25,
            "Rank (Equity Flexi Cap)": 16.0,
            "3 years": 15.2,
            "Category average (Equity Flexi Cap)": 13.5,
            "Fund returns": 13.0,
            "LT Foods Ltd.": 8.32,
            "Power Finance Corporation Ltd.": 8.01,
            "HDFC Bank Ltd.": 6.13,
            "Cholamandalam Financial Holdings Ltd.": 5.15,
            "State Bank of India": 4.87,
            "Jubilant Pharmova Ltd.": 4.71,
            "Glenmark Pharmaceuticals Ltd.": 4.66,
            "ICICI Bank Ltd.": 4.36,
            "Prestige Estates Projects Ltd.": 3.9,
            "Tilaknagar Industries Ltd.": 3.75,
            "Reliance Industries Ltd.": 3.55,
            "The South Indian Bank Ltd.": 3.35,
            "Varun Beverages Ltd.": 2.94,
            "Sanathan Textiles Ltd.": 2.94,
            "Deepak Fertilisers And Petrochemicals Corporation Ltd.": 2.93,
            "Signatureglobal (India) Ltd.": 2.68,
            "NTPC Ltd.": 2.61,
            "Angel One Ltd.": 2.55,
            "Eternal Ltd.": 2.34,
            "Larsen & Toubro Ltd.": 2.34,
        },
    },
    -14: {
        "family_id": -14, "name": "Bandhan ELSS Tax Saver",
        "category": "ELSS", "amc": "Bandhan Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 29.7,
            "Fund returns": 16.5,
            "Category average (Equity ELSS)": 14.0,
            "3 years": 8.3,
            "HDFC Bank Ltd.": 7.11,
            "Rank (Equity ELSS)": 7.0,
            "Reliance Industries Ltd.": 6.91,
            "ICICI Bank Ltd.": 4.99,
            "Kotak Mahindra Bank Ltd.": 4.77,
            "Tata Consultancy Services Ltd.": 3.98,
            "Axis Bank Ltd.": 3.39,
            "Sterlite Technologies Ltd.": 2.8,
            "Infosys Ltd.": 2.77,
            "Maruti Suzuki India Ltd.": 2.43,
            "Jindal Steel Ltd.": 2.42,
            "Bharti Airtel Ltd.": 2.35,
            "Nestle India Ltd.": 2.13,
            "State Bank of India": 2.11,
            "ITC Ltd.": 2.07,
            "Avenue Supermarts Ltd.": 2.01,
            "Mahindra & Mahindra Financial Services Ltd.": 1.93,
            "Titan Company Ltd.": 1.92,
            "Poonawalla Fincorp Ltd.": 1.77,
            "Dr. Reddy's Laboratories Ltd.": 1.65,
            "ICICI Lombard General Insurance Company Ltd.": 1.61,
        },
    },
    -15: {
        "family_id": -15, "name": "Bandhan Equity Savings",
        "category": "Equity Savings", "amc": "Bandhan Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 46.51,
            "Rank (Hybrid Equity Savings)": 19.0,
            "5 years": 18.26,
            "3 years": 8.84,
            "Category average (Hybrid Equity Savings)": 8.4,
            "Fund returns": 7.4,
            "Bandhan Money Market Fund Direct-Growth": 7.15,
            "HDFC Bank Ltd.": 4.34,
            "Multi Commodity Exchange Of India Ltd.": 4.1,
            "Axis Bank Ltd.": 3.97,
            "Indian Railway Finance Corporation Ltd.": 3.84,
            "Reliance Industries Ltd.": 3.78,
            "Kotak Mahindra Bank Ltd.": 3.66,
            "Larsen & Toubro Ltd.": 3.27,
            "Maruti Suzuki India Ltd.": 3.07,
            "ITC Ltd.": 2.69,
            "National Bank For Agriculture & Rural Development": 2.56,
            "Pidilite Industries Ltd.": 2.55,
            "GOI": 2.52,
            "State Bank of India": 2.45,
            "GOI": 2.42,
            "Bharti Airtel Ltd.": 2.3,
            "Nestle India Ltd.": 1.93,
            "Sun Pharmaceutical Industries Ltd.": 1.81,
            "Grasim Industries Ltd.": 1.67,
        },
    },
    -16: {
        "family_id": -16, "name": "Bandhan Value",
        "category": "Value", "amc": "Bandhan Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 32.71,
            "Fund returns": 16.1,
            "Category average (Equity Value Oriented)": 14.7,
            "3 years": 7.88,
            "HDFC Bank Ltd.": 7.56,
            "Reliance Industries Ltd.": 7.22,
            "Kotak Mahindra Bank Ltd.": 4.84,
            "Rank (Equity Value Oriented)": 4.0,
            "Tata Consultancy Services Ltd.": 3.75,
            "ICICI Bank Ltd.": 3.19,
            "Axis Bank Ltd.": 2.94,
            "Infosys Ltd.": 2.86,
            "Oil And Natural Gas Corporation Ltd.": 2.72,
            "Jindal Steel Ltd.": 2.47,
            "Maruti Suzuki India Ltd.": 2.35,
            "State Bank of India": 2.16,
            "NTPC Ltd.": 2.01,
            "Dr. Reddy's Laboratories Ltd.": 2.0,
            "Aurobindo Pharma Ltd.": 1.86,
            "ICICI Lombard General Insurance Company Ltd.": 1.82,
            "Poonawalla Fincorp Ltd.": 1.81,
            "Mahindra & Mahindra Financial Services Ltd.": 1.8,
            "Sterlite Technologies Ltd.": 1.79,
            "HDFC Life Insurance Co Ltd.": 1.78,
            "ITC Ltd.": 1.75,
        },
    },
    -17: {
        "family_id": -17, "name": "Bandhan Conservative Hybrid",
        "category": "Mid Cap", "amc": "Bandhan Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 39.53,
            "Rank (Hybrid Conservative Hybrid)": 19.0,
            "5 years": 15.84,
            "Bandhan Nifty 50 ETF-G Nifty 50 ETF-Growth": 11.48,
            "Fund returns": 8.0,
            "GOI": 7.93,
            "Category average (Hybrid Conservative Hybrid)": 7.8,
            "3 years": 7.51,
            "GOI": 7.25,
            "Rajasthan State": 5.28,
            "Godrej Industries Ltd.": 5.15,
            "Kotak Mahindra Prime Ltd.": 5.15,
            "REC Ltd.": 5.15,
            "National Bank For Agriculture & Rural Development": 5.14,
            "LIC Housing Finance Ltd.": 5.13,
            "Small Industries Devp. Bank of India Ltd.": 5.01,
            "Godrej Housing Finance Ltd.": 4.12,
            "Aadhar Housing Finance Ltd": 4.08,
            "GOI": 2.71,
            "Titan Company Ltd.": 2.47,
            "TVS Motor Company Ltd.": 2.15,
            "Tata Consultancy Services Ltd.": 1.79,
            "HDFC Bank Ltd.": 1.74,
            "UNO Minda Ltd.": 1.4,
            "GOI": 1.25,
        },
    },
    -18: {
        "family_id": -18, "name": "Franklin India Dynamic Accrual",
        "category": "Index", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Rank (Debt Dynamic Bond)": 15.0,
            "Fund returns": 8.3,
            "Category average (Debt Dynamic Bond)": 5.5,
        },
    },
    -19: {
        "family_id": -19, "name": "Franklin India Government Securities",
        "category": "Equity Savings", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 33.08,
            "Rank (Debt Gilt)": 20.0,
            "GOI": 19.52,
            "Maharashtra State": 18.17,
            "5 years": 15.07,
            "Reserve Bank of India": 12.14,
            "Andhra Pradesh State": 9.28,
            "Punjab State": 9.25,
            "3 years": 8.53,
            "Fund returns": 7.0,
            "Category average (Debt Gilt)": 7.0,
            "Haryana State": 6.33,
            "Rajasthan State": 3.02,
            "Bihar State": 1.95,
            "1 year": 1.8,
            "Uttarakhand State": 0.43,
            "Chhattisgarh State": 0.31,
            "West Bengal State": 0.3,
        },
    },
    -20: {
        "family_id": -20, "name": "Franklin India Small Cap",
        "category": "Small Cap", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 44.36,
            "Fund returns": 19.8,
            "Category average (Equity Small Cap)": 16.1,
            "3 years": 11.06,
            "Rank (Equity Small Cap)": 11.0,
            "1 year": 2.62,
            "Syrma SGS Technology Ltd.": 2.45,
            "MTAR Technologies Ltd.": 2.41,
            "Equitas Small Finance Bank Ltd.": 2.32,
            "Kajaria Ceramics Ltd.": 2.27,
            "Brigade Enterprises Ltd.": 2.21,
            "Eris Lifesciences Ltd.": 2.13,
            "PNB Housing Finance Ltd.": 2.05,
            "Kirloskar Oil Engines Ltd.": 2.01,
            "Aster DM Healthcare Ltd.": 1.99,
            "CESC Ltd.": 1.81,
            "Angel One Ltd.": 1.81,
            "Deepak Nitrite Ltd.": 1.74,
            "DCB Bank Ltd.": 1.64,
            "Crompton Greaves Consumer Electricals Ltd.": 1.58,
            "Sobha Ltd.": 1.57,
            "Zensar Technologies Ltd.": 1.55,
            "Data Patterns (India) Ltd.": 1.54,
            "CCL Products (India) Ltd.": 1.51,
            "Medplus Health Services Ltd.": 1.49,
        },
    },
    -21: {
        "family_id": -21, "name": "Franklin India Dividend Yield",
        "category": "Thematic", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 34.23,
            "Category average (Equity Thematic)": 15.2,
            "Fund returns": 14.9,
            "3 years": 9.87,
            "State Bank of India": 5.33,
            "NTPC Ltd.": 4.59,
            "HDFC Bank Ltd.": 4.35,
            "Embassy Office Parks REIT": 3.99,
            "ICICI Bank Ltd.": 3.84,
            "Infosys Ltd.": 3.69,
            "Oil And Natural Gas Corporation Ltd.": 3.2,
            "Coal India Ltd.": 3.12,
            "HCL Technologies Ltd.": 3.07,
            "MediaTek (Taiwan)": 2.72,
            "Bharat Electronics Ltd.": 2.43,
            "Tata Consultancy Services Ltd.": 2.39,
            "CESC Ltd.": 2.28,
            "NHPC Ltd.": 2.17,
            "Tata Steel Ltd.": 2.15,
            "GAIL (India) Ltd.": 2.11,
            "Knowledge Realty Trust": 2.07,
            "ITC Ltd.": 2.05,
            "REC Ltd.": 2.0,
            "Rank (Equity Thematic)": 2.0,
            "Britannia Industries Ltd.": 1.99,
        },
    },
    -22: {
        "family_id": -22, "name": "Franklin India Large Cap",
        "category": "Large Cap", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 78.37,
            "Rank (Equity Large Cap)": 41.0,
            "5 years": 22.35,
            "Category average (Equity Large Cap)": 13.2,
            "Fund returns": 12.0,
            "ICICI Bank Ltd.": 8.33,
            "HDFC Bank Ltd.": 6.77,
            "3 years": 6.73,
            "Reliance Industries Ltd.": 5.81,
            "Eternal Ltd.": 4.67,
            "Kotak Mahindra Bank Ltd.": 4.3,
            "Axis Bank Ltd.": 4.06,
            "Mahindra & Mahindra Ltd.": 3.82,
            "Larsen & Toubro Ltd.": 3.82,
            "Infosys Ltd.": 3.64,
            "State Bank of India": 3.47,
            "SBI Life Insurance Company Ltd.": 3.0,
            "Tata Power Company Ltd.": 2.41,
            "JB Chemicals & Pharmaceuticals Ltd.": 2.2,
            "HCL Technologies Ltd.": 2.16,
            "Asian Paints Ltd.": 2.02,
            "Hindalco Industries Ltd.": 1.78,
            "Ultratech Cement Ltd.": 1.74,
            "PB Fintech Ltd.": 1.59,
            "Power Grid Corporation Of India Ltd.": 1.56,
        },
    },
    -23: {
        "family_id": -23, "name": "Franklin India Mid Cap",
        "category": "Mid Cap", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 42.96,
            "Fund returns": 17.9,
            "Category average (Equity Mid Cap)": 16.0,
            "Rank (Equity Mid Cap)": 15.0,
            "3 years": 14.1,
            "The Federal Bank Ltd.": 2.45,
            "Mphasis Ltd.": 2.17,
            "Biocon Ltd.": 2.15,
            "IDFC First Bank Ltd.": 2.12,
            "Balkrishna Industries Ltd.": 2.1,
            "Tube Investments Of India Ltd.": 2.04,
            "Mankind Pharma Ltd.": 1.91,
            "Prestige Estates Projects Ltd.": 1.91,
            "Mahindra & Mahindra Financial Services Ltd.": 1.9,
            "APL Apollo Tubes Ltd.": 1.89,
            "ICICI Lombard General Insurance Company Ltd.": 1.89,
            "Ipca Laboratories Ltd.": 1.86,
            "Tata Steel Ltd.": 1.72,
            "Shree Cement Ltd.": 1.67,
            "Ashok Leyland Ltd.": 1.65,
            "The Phoenix Mills Ltd.": 1.65,
            "Deepak Nitrite Ltd.": 1.58,
            "SRF Ltd.": 1.52,
            "Kalyan Jewellers India Ltd.": 1.5,
            "Page Industries Ltd.": 1.47,
        },
    },
    -24: {
        "family_id": -24, "name": "Franklin India Large & Mid Cap",
        "category": "Large & MidCap", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 92.85,
            "5 years": 28.34,
            "Rank (Equity Large & MidCap)": 18.0,
            "Category average (Equity Large & MidCap)": 14.7,
            "Fund returns": 13.8,
            "3 years": 9.56,
            "Eternal Ltd.": 3.94,
            "HDFC Bank Ltd.": 2.95,
            "ICICI Bank Ltd.": 2.9,
            "Kotak Mahindra Bank Ltd.": 2.86,
            "JB Chemicals & Pharmaceuticals Ltd.": 2.8,
            "Mahindra & Mahindra Ltd.": 2.75,
            "Axis Bank Ltd.": 2.48,
            "State Bank of India": 2.46,
            "PB Fintech Ltd.": 2.4,
            "AU Small Finance Bank Ltd.": 2.32,
            "Vishal Mega Mart Ltd.": 2.19,
            "Marico Ltd.": 2.11,
            "Persistent Systems Ltd.": 2.02,
            "Colgate-Palmolive (India) Ltd.": 2.01,
            "Crompton Greaves Consumer Electricals Ltd.": 1.99,
            "Canara HSBC Life Insurance Company Ltd.": 1.97,
            "Apollo Hospitals Enterprise Ltd.": 1.96,
            "Max Financial Services Ltd.": 1.94,
            "Swiggy Ltd.": 1.9,
        },
    },
    -25: {
        "family_id": -25, "name": "Franklin India Technology",
        "category": "Sectoral", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Bharti Airtel Ltd.": 18.68,
            "5 years": 18.07,
            "Category average (Equity Sectoral)": 17.2,
            "Fund returns": 16.9,
            "Infosys Ltd.": 14.98,
            "Franklin Technology Fund I (Acc) USD": 7.17,
            "Eternal Ltd.": 6.78,
            "HCL Technologies Ltd.": 6.51,
            "Tata Consultancy Services Ltd.": 5.68,
            "PB Fintech Ltd.": 5.23,
            "Rank (Equity Sectoral)": 5.0,
            "Cognizant Technology Solutions Corp.": 4.85,
            "Meesho Ltd.": 2.84,
            "Amagi Media Labs Ltd.": 2.75,
            "Info Edge (India) Ltd.": 2.33,
            "Swiggy Ltd.": 2.21,
            "MakeMy Trip Ltd.": 2.14,
            "Intellect Design Arena Ltd.": 2.04,
            "Alphabet Inc Class A": 2.02,
            "Zensar Technologies Ltd.": 2.0,
            "Mphasis Ltd.": 1.86,
            "Amazon. com Inc. (USA)": 1.25,
            "Apple Inc. (USA)": 1.18,
            "Meta Platforms Inc": 1.09,
            "Hexaware Technologies Ltd.": 1.06,
        },
    },
    -26: {
        "family_id": -26, "name": "Franklin India Opportunities Direct",
        "category": "Thematic", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 60.01,
            "3 years": 18.87,
            "Fund returns": 17.1,
            "Category average (Equity Thematic)": 13.6,
            "Reliance Industries Ltd.": 5.15,
            "Hindustan Aeronautics Ltd.": 4.94,
            "Shriram Finance Ltd": 4.07,
            "Axis Bank Ltd.": 3.88,
            "Amphenol Corp": 3.84,
            "State Bank of India": 3.72,
            "APL Apollo Tubes Ltd.": 3.71,
            "NTPC Ltd.": 3.5,
            "Mankind Pharma Ltd.": 3.24,
            "AIA Engineering Ltd.": 2.63,
            "Kirloskar Oil Engines Ltd.": 2.56,
            "Eternal Ltd.": 2.44,
            "Amber Enterprises India Ltd.": 2.38,
            "Syrma SGS Technology Ltd.": 2.28,
            "PB Fintech Ltd.": 2.12,
            "IDFC First Bank Ltd.": 2.11,
            "Rank (Equity Thematic)": 2.0,
            "PG Electroplast Ltd.": 1.92,
            "Aster DM Healthcare Ltd.": 1.88,
            "Tata Motors Passenger Vehicles Ltd.": 1.81,
            "Ujjivan Small Finance Bank Ltd.": 1.8,
        },
    },
    -27: {
        "family_id": -27, "name": "Franklin India ELSS Tax Saver",
        "category": "ELSS", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 30.0,
            "Rank (Equity ELSS)": 21.0,
            "Fund returns": 14.8,
            "Category average (Equity ELSS)": 14.0,
            "HDFC Bank Ltd.": 8.24,
            "ICICI Bank Ltd.": 6.82,
            "3 years": 6.42,
            "Axis Bank Ltd.": 5.15,
            "State Bank of India": 4.96,
            "Larsen & Toubro Ltd.": 4.72,
            "Infosys Ltd.": 3.7,
            "Bharti Airtel Ltd.": 3.52,
            "Reliance Industries Ltd.": 3.45,
            "Grasim Industries Ltd.": 3.13,
            "Kotak Mahindra Bank Ltd.": 3.13,
            "Eternal Ltd.": 3.03,
            "HCL Technologies Ltd.": 2.97,
            "Bharat Electronics Ltd.": 2.93,
            "Mahindra & Mahindra Ltd.": 2.83,
            "Apollo Hospitals Enterprise Ltd.": 2.44,
            "NTPC Ltd.": 2.28,
            "Kirloskar Oil Engines Ltd.": 2.24,
            "Marico Ltd.": 2.2,
            "Tata Power Company Ltd.": 2.18,
            "PB Fintech Ltd.": 1.76,
        },
    },
    -28: {
        "family_id": -28, "name": "Franklin India Aggressive Hybrid",
        "category": "Aggressive Hybrid", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 85.55,
            "5 years": 26.29,
            "Rank (Hybrid Aggressive Hybrid)": 17.0,
            "Fund returns": 13.5,
            "Category average (Hybrid Aggressive Hybrid)": 12.0,
            "3 years": 7.88,
            "HDFC Bank Ltd.": 5.15,
            "ICICI Bank Ltd.": 4.93,
            "Jubilant Bevco Ltd.": 4.72,
            "Reliance Industries Ltd.": 4.1,
            "Axis Bank Ltd.": 3.58,
            "State Bank of India": 3.29,
            "Bharti Airtel Ltd.": 3.03,
            "Larsen & Toubro Ltd.": 3.01,
            "Jubilant Beverages Ltd.": 2.88,
            "NTPC Ltd.": 2.25,
            "Infosys Ltd.": 2.23,
            "Poonawalla Fincorp Ltd.": 2.17,
            "Mahindra & Mahindra Ltd.": 1.88,
            "HCL Technologies Ltd.": 1.87,
            "Eternal Ltd.": 1.82,
            "Ultratech Cement Ltd.": 1.71,
            "Tata Steel Ltd.": 1.65,
            "Bharti Telecom Ltd.": 1.6,
            "Marico Ltd.": 1.55,
        },
    },
    -29: {
        "family_id": -29, "name": "Franklin Build India",
        "category": "Sectoral", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 62.0,
            "Fund returns": 20.6,
            "3 years": 18.53,
            "Category average (Equity Sectoral)": 15.4,
            "Rank (Equity Sectoral)": 8.0,
            "Larsen & Toubro Ltd.": 7.49,
            "Oil And Natural Gas Corporation Ltd.": 6.36,
            "Reliance Industries Ltd.": 5.79,
            "NTPC Ltd.": 5.71,
            "Interglobe Aviation Ltd.": 5.61,
            "Power Grid Corporation Of India Ltd.": 4.31,
            "Bharti Airtel Ltd.": 4.17,
            "Axis Bank Ltd.": 3.95,
            "HDFC Bank Ltd.": 3.9,
            "REC Ltd.": 3.1,
            "Tata Power Company Ltd.": 3.04,
            "State Bank of India": 2.83,
            "Delhivery Ltd.": 2.62,
            "Tata Steel Ltd.": 2.6,
            "Sobha Ltd.": 2.44,
            "Kirloskar Oil Engines Ltd.": 2.14,
            "Kei Industries Ltd.": 2.12,
            "APL Apollo Tubes Ltd.": 1.99,
            "Hindustan Aeronautics Ltd.": 1.92,
            "Kirloskar Pneumatic Company Ltd.": 1.75,
        },
    },
    -30: {
        "family_id": -30, "name": "Franklin Asian Equity",
        "category": "Index", "amc": "Franklin Templeton Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 83.88,
            "5 years": 56.88,
            "3 years": 50.76,
            "1 year": 23.34,
            "Rank (Equity International)": 17.0,
            "Category average (Equity International)": 11.5,
            "Fund returns": 10.4,
            "Taiwan Semiconductor Manufacturing Co Ltd. (Taiwan)": 8.98,
            "Samsung Electronics Co Ltd. (South Korea)": 5.97,
            "SK Hynix Inc": 4.07,
            "ICICI Bank Ltd.": 3.57,
            "Tencent Holdings Ltd.": 3.18,
            "MediaTek (Taiwan)": 2.86,
            "Larsen & Toubro Ltd.": 2.65,
            "HDFC Bank Ltd.": 2.26,
            "Alibaba Group Holdings Ltd.": 2.18,
            "Hyundai Motor (South Korea)": 2.15,
            "Contemporary Amperex Technology Co Ltd.": 2.11,
            "Torrent Pharmaceuticals Ltd.": 1.93,
            "Weichai Power Ltd. (China)": 1.92,
            "Eternal Ltd.": 1.9,
            "Max Healthcare Institute Ltd.": 1.88,
            "Yageo Corp": 1.57,
            "Reliance Industries Ltd.": 1.56,
            "Tata Capital Ltd.": 1.55,
        },
    },
    -31: {
        "family_id": -31, "name": "Edelweiss Large Cap",
        "category": "Large Cap", "amc": "Edelweiss Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 98.65,
            "5 years": 27.13,
            "Fund returns": 13.9,
            "Category average (Equity Large Cap)": 13.2,
            "Rank (Equity Large Cap)": 7.0,
            "3 years": 6.86,
            "HDFC Bank Ltd.": 6.77,
            "ICICI Bank Ltd.": 6.23,
            "Reliance Industries Ltd.": 5.81,
            "Larsen & Toubro Ltd.": 4.47,
            "Bharti Airtel Ltd.": 3.72,
            "State Bank of India": 3.63,
            "Bajaj Finance Ltd.": 3.19,
            "Mahindra & Mahindra Ltd.": 3.01,
            "Infosys Ltd.": 2.59,
            "Titan Company Ltd.": 2.57,
            "NTPC Ltd.": 2.39,
            "Axis Bank Ltd.": 2.38,
            "ITC Ltd.": 2.19,
            "Apollo Hospitals Enterprise Ltd.": 1.81,
            "Muthoot Finance Ltd.": 1.73,
            "Ultratech Cement Ltd.": 1.7,
            "Maruti Suzuki India Ltd.": 1.51,
            "GE Vernova T&D India Ltd": 1.42,
            "Sun Pharmaceutical Industries Ltd.": 1.26,
        },
    },
    -32: {
        "family_id": -32, "name": "Edelweiss ELSS Tax Saver",
        "category": "ELSS", "amc": "Edelweiss Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 37.0,
            "Fund returns": 14.6,
            "3 years": 14.46,
            "Category average (Equity ELSS)": 14.0,
            "Rank (Equity ELSS)": 14.0,
            "Reliance Industries Ltd.": 5.07,
            "HDFC Bank Ltd.": 4.41,
            "Bharti Airtel Ltd.": 3.63,
            "Larsen & Toubro Ltd.": 3.07,
            "ICICI Bank Ltd.": 2.96,
            "Multi Commodity Exchange Of India Ltd.": 2.9,
            "BSE Ltd.": 2.9,
            "State Bank of India": 2.72,
            "Muthoot Finance Ltd.": 2.23,
            "NTPC Ltd.": 2.23,
            "Bharat Electronics Ltd.": 2.17,
            "Ather Energy Ltd.": 1.72,
            "Mahindra & Mahindra Ltd.": 1.72,
            "Sun Pharmaceutical Industries Ltd.": 1.63,
            "Karur Vysya Bank Ltd.": 1.61,
            "Infosys Ltd.": 1.49,
            "Trent Ltd.": 1.45,
            "Torrent Pharmaceuticals Ltd.": 1.4,
            "Gabriel India Ltd.": 1.38,
            "Netweb Technologies India Ltd.": 1.31,
        },
    },
    -33: {
        "family_id": -33, "name": "Edelweiss Equity Savings",
        "category": "Equity Savings", "amc": "Edelweiss Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 70.24,
            "5 years": 28.24,
            "3 years": 14.38,
            "Fund returns": 9.7,
            "Category average (Hybrid Equity Savings)": 8.4,
            "HDFC Bank Ltd.": 5.06,
            "Steel Authority Of India Ltd.": 4.22,
            "Reliance Industries Ltd.": 4.01,
            "Rank (Hybrid Equity Savings)": 4.0,
            "Edelweiss Liquid Super Institutional Direct-Growth": 3.92,
            "HDB Financial Services Ltd.": 3.8,
            "Bharti Airtel Ltd.": 3.7,
            "Adani Green Energy Ltd.": 3.36,
            "ICICI Bank Ltd.": 3.35,
            "1 year": 2.9,
            "Edelweiss Low Duration Fund Direct-Growth": 2.79,
            "Edelweiss Money Market Fund Direct-Growth": 2.78,
            "Vodafone Idea Ltd.": 2.47,
            "UPL Ltd.": 2.39,
            "Brookfield India Real Estate Trust REIT": 2.31,
            "GOI": 1.92,
            "Bharti Telecom Ltd.": 1.89,
            "Bajaj Finance Ltd.": 1.89,
            "IndiGrid Infrastructure Trust": 1.39,
            "Adani Ports and Special Economic Zone Ltd.": 1.26,
        },
    },
    -34: {
        "family_id": -34, "name": "Edelweiss Money Market",
        "category": "Balanced Advantage", "amc": "Edelweiss Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 40.51,
            "5 years": 18.01,
            "Rank (Debt Money Market)": 15.0,
            "3 years": 10.39,
            "Fund returns": 7.4,
            "Category average (Debt Money Market)": 6.5,
            "National Bank For Agriculture & Rural Development": 6.3,
            "HDFC Bank Ltd.": 6.28,
            "Axis Bank Ltd.": 5.34,
            "ICICI Bank Ltd.": 5.22,
            "Reserve Bank of India": 4.35,
            "Bank Of Baroda": 4.33,
            "Punjab National Bank": 4.33,
            "Small Industries Devp. Bank of India Ltd.": 4.2,
            "Canara Bank": 4.19,
            "The Federal Bank Ltd.": 4.18,
            "HDFC Bank Ltd.": 3.21,
            "1 year": 2.53,
            "Reserve Bank of India": 2.41,
            "Indian Bank": 2.15,
            "Small Industries Devp. Bank of India Ltd.": 2.14,
            "Small Industries Devp. Bank of India Ltd.": 2.13,
            "Axis Bank Ltd.": 2.13,
            "Indian Bank": 2.11,
            "Motilal Oswal Financial Services Ltd.": 2.1,
        },
    },
    -35: {
        "family_id": -35, "name": "Mirae Asset Large Cap",
        "category": "Large Cap", "amc": "Mirae Asset Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 85.18,
            "5 years": 21.43,
            "Fund returns": 15.0,
            "Category average (Equity Large Cap)": 13.2,
            "Rank (Equity Large Cap)": 10.0,
            "HDFC Bank Ltd.": 9.15,
            "ICICI Bank Ltd.": 8.12,
            "3 years": 6.22,
            "Reliance Industries Ltd.": 5.76,
            "Bharti Airtel Ltd.": 4.99,
            "Infosys Ltd.": 4.09,
            "Larsen & Toubro Ltd.": 3.47,
            "State Bank of India": 3.42,
            "Axis Bank Ltd.": 3.37,
            "ITC Ltd.": 2.83,
            "Eternal Ltd.": 2.48,
            "Maruti Suzuki India Ltd.": 2.43,
            "Tata Consultancy Services Ltd.": 2.26,
            "Mahindra & Mahindra Ltd.": 2.25,
            "Kotak Mahindra Bank Ltd.": 1.67,
            "Asian Paints Ltd.": 1.6,
            "Ambuja Cements Ltd.": 1.59,
            "Varun Beverages Ltd.": 1.41,
            "Apollo Hospitals Enterprise Ltd.": 1.39,
            "One97 Communications Ltd.": 1.38,
        },
    },
    -36: {
        "family_id": -36, "name": "Mirae Asset China Advantage",
        "category": "Index", "amc": "Mirae Asset Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Fund returns": 3.0,
        },
    },
    -37: {
        "family_id": -37, "name": "Mirae Asset Great Consumer",
        "category": "Thematic", "amc": "Mirae Asset Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 29.73,
            "Fund returns": 16.5,
            "Category average (Equity Thematic)": 14.5,
            "Eternal Ltd.": 6.69,
            "Titan Company Ltd.": 6.68,
            "Maruti Suzuki India Ltd.": 6.59,
            "Mahindra & Mahindra Ltd.": 6.53,
            "Bharti Airtel Ltd.": 6.35,
            "3 years": 5.76,
            "ITC Ltd.": 4.75,
            "Trent Ltd.": 4.64,
            "Varun Beverages Ltd.": 4.05,
            "Eicher Motors Ltd.": 4.0,
            "Asian Paints Ltd.": 3.57,
            "Britannia Industries Ltd.": 3.32,
            "Avenue Supermarts Ltd.": 3.09,
            "Vishal Mega Mart Ltd.": 2.74,
            "Crompton Greaves Consumer Electricals Ltd.": 2.63,
            "LG Electronics India Ltd.": 2.52,
            "Apollo Hospitals Enterprise Ltd.": 2.4,
            "Godrej Consumer Products Ltd.": 2.32,
            "Campus Activewear Ltd.": 2.13,
            "Marico Ltd.": 2.08,
            "Honasa Consumer Ltd.": 2.07,
            "Rank (Equity Thematic)": 2.0,
        },
    },
    -38: {
        "family_id": -38, "name": "Taurus ELSS Tax Saver",
        "category": "ELSS", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 88.72,
            "5 years": 26.4,
            "Rank (Equity ELSS)": 20.0,
            "Category average (Equity ELSS)": 14.0,
            "Fund returns": 12.6,
            "ITC Ltd.": 8.47,
            "Bajaj Holdings & Investment Ltd.": 7.53,
            "HDFC Bank Ltd.": 7.53,
            "Power Grid Corporation Of India Ltd.": 6.51,
            "ICICI Bank Ltd.": 6.5,
            "3 years": 5.74,
            "Divi's Laboratories Ltd.": 5.71,
            "Indian Energy Exchange Ltd.": 5.65,
            "Pace Digitek Ltd.": 5.37,
            "Coal India Ltd.": 4.76,
            "Narayana Hrudayalaya Ltd.": 3.91,
            "Mahindra & Mahindra Ltd.": 3.21,
            "Axis Bank Ltd.": 3.11,
            "Park Medi World Ltd.": 2.77,
            "Mazagon Dock Shipbuilders Ltd.": 2.59,
            "Insolation Energy Ltd.": 2.4,
            "Bharti Airtel Ltd.": 2.36,
            "Power Finance Corporation Ltd.": 2.21,
            "Oracle Financial Services Software Ltd.": 2.07,
            "Reliance Industries Ltd.": 1.95,
        },
    },
    -39: {
        "family_id": -39, "name": "Taurus Large Cap",
        "category": "Large Cap", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 70.21,
            "Rank (Equity Large Cap)": 42.0,
            "5 years": 24.22,
            "Category average (Equity Large Cap)": 13.2,
            "Fund returns": 10.1,
            "ITC Ltd.": 9.39,
            "Divi's Laboratories Ltd.": 7.65,
            "3 years": 7.06,
            "HDFC Bank Ltd.": 6.3,
            "ICICI Bank Ltd.": 6.02,
            "Bharti Airtel Ltd.": 4.71,
            "State Bank of India": 4.12,
            "Mazagon Dock Shipbuilders Ltd.": 3.94,
            "Reliance Industries Ltd.": 3.78,
            "Power Grid Corporation Of India Ltd.": 3.62,
            "Oil And Natural Gas Corporation Ltd.": 3.26,
            "DLF Ltd.": 2.73,
            "PVR Inox Ltd.": 2.66,
            "Mahindra & Mahindra Ltd.": 2.65,
            "Axis Bank Ltd.": 2.52,
            "The Indian Hotels Company Ltd.": 2.31,
            "HCL Technologies Ltd.": 2.31,
            "Coal India Ltd.": 2.2,
            "Solar Industries India Ltd.": 2.02,
            "Tata Power Company Ltd.": 1.97,
        },
    },
    -40: {
        "family_id": -40, "name": "Taurus Mid Cap",
        "category": "Mid Cap", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 26.54,
            "Category average (Equity Mid Cap)": 16.0,
            "Rank (Equity Mid Cap)": 16.0,
            "Fund returns": 15.6,
            "Linde India Ltd.": 6.04,
            "Persistent Systems Ltd.": 4.67,
            "Aurobindo Pharma Ltd.": 4.64,
            "The Federal Bank Ltd.": 4.28,
            "Pace Digitek Ltd.": 4.16,
            "3 years": 3.91,
            "REC Ltd.": 3.64,
            "Coforge Ltd.": 3.56,
            "GMR Airports Ltd.": 3.53,
            "PI Industries Ltd.": 3.36,
            "Container Corporation Of India Ltd.": 3.21,
            "Petronet LNG Ltd.": 3.16,
            "Insolation Energy Ltd.": 3.13,
            "Vodafone Idea Ltd.": 3.01,
            "Bharat Heavy Electricals Ltd.": 2.89,
            "Deepak Nitrite Ltd.": 2.76,
            "Torrent Power Ltd.": 2.76,
            "Regaal Resources Ltd.": 2.68,
            "Abbott India Ltd.": 2.66,
            "Bank of India": 2.62,
            "Inox Wind Ltd.": 2.56,
        },
    },
    -41: {
        "family_id": -41, "name": "Taurus Ethical",
        "category": "Thematic", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 27.59,
            "Fund returns": 14.3,
            "Category average (Equity Thematic)": 13.6,
            "3 years": 8.22,
            "Reliance Industries Ltd.": 8.1,
            "Tata Consultancy Services Ltd.": 5.07,
            "Infosys Ltd.": 4.36,
            "Rank (Equity Thematic)": 4.0,
            "Oracle Financial Services Software Ltd.": 3.54,
            "Hindustan Unilever Ltd.": 3.46,
            "Linde India Ltd.": 3.27,
            "Dixon Technologies (India) Ltd.": 3.24,
            "Tube Investments Of India Ltd.": 2.98,
            "Coal India Ltd.": 2.9,
            "Torrent Power Ltd.": 2.66,
            "Persistent Systems Ltd.": 2.61,
            "Laurus Labs Ltd.": 2.52,
            "TVS Motor Company Ltd.": 2.24,
            "HCL Technologies Ltd.": 2.21,
            "Cipla Ltd.": 2.19,
            "Colgate-Palmolive (India) Ltd.": 2.12,
            "Mahindra & Mahindra Ltd.": 2.06,
            "Bharat Petroleum Corporation Ltd.": 1.98,
            "Larsen & Toubro Ltd.": 1.95,
            "Vikram Solar Ltd.": 1.88,
        },
    },
    -42: {
        "family_id": -42, "name": "Taurus Infrastructure",
        "category": "Sectoral", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 32.69,
            "Rank (Equity Sectoral)": 17.0,
            "Category average (Equity Sectoral)": 15.4,
            "Fund returns": 13.4,
            "Bharti Airtel Ltd": 10.26,
            "Larsen & Toubro Ltd": 7.66,
            "Reliance Industries Ltd": 7.63,
            "3 years": 7.44,
            "Power Grid Corporation of India Ltd": 5.97,
            "NTPC Ltd": 3.89,
            "Insolation Energy Ltd": 3.76,
            "Oil & Natural Gas Corporation Ltd": 3.76,
            "Ultratech Cement Ltd": 3.6,
            "Le Travenues Technology Ltd.": 3.48,
            "Grasim Industries Ltd": 3.15,
            "Adani Enterprises Ltd": 3.13,
            "Vodafone Idea Ltd": 2.9,
            "SAMHI Hotels Ltd.": 2.69,
            "BEML Ltd": 2.66,
            "Steel Authority Of India Ltd": 2.62,
            "Chemtech Industrial Valves Ltd": 2.49,
            "Mazagon Dock Shipbuilders Ltd": 2.41,
            "Bharat Petroleum Corporation Ltd": 2.3,
            "Interglobe Aviation Ltd": 2.24,
            "Indian Energy Exchange Ltd": 2.14,
        },
    },
    -43: {
        "family_id": -43, "name": "Taurus Flexi Cap",
        "category": "Flexi Cap", "amc": "Unknown",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 64.0,
            "Rank (Equity Flexi Cap)": 36.0,
            "5 years": 22.0,
            "Category average (Equity Flexi Cap)": 13.5,
            "Fund returns": 9.9,
            "ITC Ltd.": 7.96,
            "HDFC Bank Ltd.": 7.61,
            "Divi's Laboratories Ltd.": 5.2,
            "3 years": 4.84,
            "ICICI Bank Ltd.": 4.27,
            "Park Medi World Ltd.": 3.92,
            "Bharti Airtel Ltd.": 3.71,
            "SAMHI Hotels Ltd.": 3.67,
            "Axis Bank Ltd.": 3.61,
            "Mahindra & Mahindra Ltd.": 3.39,
            "Reliance Industries Ltd.": 3.35,
            "Narayana Hrudayalaya Ltd.": 3.27,
            "State Bank of India": 3.18,
            "Power Grid Corporation Of India Ltd.": 3.04,
            "Linde India Ltd.": 2.96,
            "Pace Digitek Ltd.": 2.93,
            "Kotak Mahindra Bank Ltd.": 2.76,
            "Ambika Cotton Mills Ltd.": 2.68,
            "Bajaj Holdings & Investment Ltd.": 2.59,
            "Coal India Ltd.": 2.31,
        },
    },
    -44: {
        "family_id": -44, "name": "HDFC Long Term Advantage",
        "category": "ELSS", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Fund returns": 17.3,
            "Category average (Equity ELSS)": 16.5,
            "Infosys Ltd": 9.71,
            "ICICI Bank Ltd": 9.48,
            "Reliance Industries Ltd": 9.03,
            "HDFC Bank Ltd": 9.02,
            "Housing Development Finance Corporation Ltd": 7.89,
            "State Bank of India": 7.37,
            "Larsen & Toubro Ltd": 5.49,
            "ITC Ltd": 4.69,
            "Carborundum Universal Ltd": 4.49,
            "Redington Ltd": 4.31,
            "Vesuvius India Ltd": 3.2,
            "Power Grid Corporation of India Ltd": 3.12,
            "Bharat Petroleum Corporation Ltd": 2.94,
            "Tata Motors DVR": 2.76,
            "Bharti Airtel Ltd": 2.68,
            "Aurobindo Pharma Ltd": 2.24,
            "HDFC BSE Sensex ETF": 2.0,
            "Oriental Carbon & Chemicals Ltd": 1.95,
            "Repo": 1.56,
            "Cholamandalam Financial Holdings Ltd": 1.46,
            "Bank Of Baroda": 1.01,
            "Net Current Assets": 0.95,
            "eClerx Services Ltd": 0.85,
        },
    },
    -45: {
        "family_id": -45, "name": "HDFC Balanced",
        "category": "Aggressive Hybrid", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Fund returns": 19.8,
            "Category average (Hybrid Aggressive Hybrid)": 13.9,
            "HDFC Bank Ltd.": 6.5,
            "Infosys Ltd.": 3.82,
            "Housing Development Finance Corpn. Ltd.": 3.38,
            "ITC Ltd.": 3.25,
            "Larsen & Toubro Ltd.": 3.1,
            "ICICI Bank Ltd.": 2.96,
            "Aurobindo Pharma Ltd.": 1.94,
            "Indusind Bank Ltd.": 1.77,
            "Axis Bank Ltd.": 1.76,
            "Voltas Ltd.": 1.75,
            "State Bank of India": 1.47,
            "Power Grid Corporation of India Ltd.": 1.47,
            "GOI": 1.43,
            "Aarti Industries Ltd.": 1.4,
            "Vedanta Ltd.": 1.37,
            "Bharat Electronics Ltd.": 1.34,
            "SKF India Ltd.": 1.32,
            "Tata Sons Ltd.": 1.32,
            "Cholamandalam Financial Holdings Ltd.": 1.3,
            "Hindustan Petroleum Corpn. Ltd.": 1.28,
            "Tata Steel Ltd.": 1.27,
            "L&T Infrastructure Finance Co. Ltd.": 1.26,
            "Balkrishna Industries Ltd.": 1.24,
        },
    },
    -46: {
        "family_id": -46, "name": "HDFC Value",
        "category": "Value", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 39.72,
            "Fund returns": 15.7,
            "Category average (Equity Value Oriented)": 14.7,
            "3 years": 14.43,
            "Rank (Equity Value Oriented)": 10.0,
            "ICICI Bank Ltd.": 6.47,
            "HDFC Bank Ltd.": 5.45,
            "Axis Bank Ltd.": 4.2,
            "State Bank of India": 3.94,
            "Bharti Airtel Ltd.": 3.35,
            "Larsen & Toubro Ltd.": 2.88,
            "Infosys Ltd.": 2.82,
            "NTPC Ltd.": 2.72,
            "AU Small Finance Bank Ltd.": 2.55,
            "Bharat Electronics Ltd.": 2.36,
            "Reliance Industries Ltd.": 2.35,
            "Sun Pharmaceutical Industries Ltd.": 2.22,
            "SBI Life Insurance Company Ltd.": 2.11,
            "Tech Mahindra Ltd.": 1.71,
            "The Phoenix Mills Ltd.": 1.61,
            "Multi Commodity Exchange Of India Ltd.": 1.58,
            "HCL Technologies Ltd.": 1.53,
            "Prestige Estates Projects Ltd.": 1.53,
            "Lupin Ltd.": 1.49,
            "Eternal Ltd.": 1.48,
        },
    },
    -47: {
        "family_id": -47, "name": "HDFC Focused",
        "category": "Flexi Cap", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 45.48,
            "Fund returns": 14.6,
            "Category average (Equity Flexi Cap)": 13.5,
            "3 years": 12.85,
            "Rank (Equity Flexi Cap)": 10.0,
            "ICICI Bank Ltd.": 9.02,
            "HDFC Bank Ltd.": 8.41,
            "Axis Bank Ltd.": 7.27,
            "State Bank of India": 5.76,
            "Kotak Mahindra Bank Ltd.": 5.53,
            "HCL Technologies Ltd.": 3.89,
            "Bharti Airtel Ltd.": 3.69,
            "Maruti Suzuki India Ltd.": 3.58,
            "SBI Life Insurance Company Ltd.": 3.58,
            "Eternal Ltd.": 3.53,
            "Cipla Ltd.": 3.49,
            "Power Grid Corporation Of India Ltd.": 3.28,
            "Eicher Motors Ltd.": 3.24,
            "Interglobe Aviation Ltd.": 3.05,
            "Tata Steel Ltd.": 2.58,
            "Havells India Ltd.": 2.54,
            "Karur Vysya Bank Ltd.": 2.11,
            "FSN E-Commerce Ventures Ltd.": 2.02,
            "Nexus Select Trust": 1.78,
            "Bosch Ltd.": 1.73,
        },
    },
    -48: {
        "family_id": -48, "name": "HDFC Balanced Advantage",
        "category": "Balanced Advantage", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 36.04,
            "Fund returns": 14.6,
            "Category average (Hybrid Dynamic Asset Allocation)": 9.6,
            "3 years": 9.48,
            "ICICI Bank Ltd.": 4.47,
            "HDFC Bank Ltd.": 4.14,
            "Reliance Industries Ltd.": 4.09,
            "State Bank of India": 3.55,
            "Bharti Airtel Ltd.": 3.1,
            "Larsen & Toubro Ltd.": 2.51,
            "NTPC Ltd.": 2.41,
            "Axis Bank Ltd.": 2.4,
            "GOI": 2.1,
            "Coal India Ltd.": 2.02,
            "Infosys Ltd.": 1.82,
            "GOI": 1.46,
            "Maruti Suzuki India Ltd.": 1.44,
            "Sun Pharmaceutical Industries Ltd.": 1.43,
            "Kotak Mahindra Bank Ltd.": 1.39,
            "Eternal Ltd.": 1.27,
            "ITC Ltd.": 1.24,
            "Lupin Ltd.": 1.24,
            "HCL Technologies Ltd.": 1.15,
            "Tata Consultancy Services Ltd.": 1.15,
            "Rank (Hybrid Dynamic Asset Allocation)": 1.0,
        },
    },
    -49: {
        "family_id": -49, "name": "HDFC Infrastructure",
        "category": "Sectoral", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 59.23,
            "Rank (Equity Sectoral)": 19.0,
            "Category average (Equity Sectoral)": 15.4,
            "3 years": 14.21,
            "Fund returns": 12.2,
            "Larsen & Toubro Ltd.": 6.99,
            "ICICI Bank Ltd.": 5.39,
            "Kalpataru Projects International Ltd.": 4.03,
            "NTPC Ltd.": 3.88,
            "Power Grid Corporation Of India Ltd.": 3.16,
            "Reliance Industries Ltd.": 3.14,
            "J Kumar Infraprojects Ltd.": 3.01,
            "Interglobe Aviation Ltd.": 2.78,
            "TD Power Systems Ltd.": 2.62,
            "Coal India Ltd.": 2.59,
            "Adani Ports and Special Economic Zone Ltd.": 2.54,
            "Bharti Airtel Ltd.": 2.5,
            "GR Infraprojects Ltd.": 2.21,
            "Tata Steel Ltd.": 2.19,
            "State Bank of India": 1.99,
            "HDFC Bank Ltd.": 1.92,
            "Ambuja Cements Ltd.": 1.75,
            "Axis Bank Ltd.": 1.73,
            "Power Finance Corporation Ltd.": 1.72,
            "NCC Ltd.": 1.59,
        },
    },
    -50: {
        "family_id": -50, "name": "HDFC Mid Cap",
        "category": "Mid Cap", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 58.68,
            "Fund returns": 20.2,
            "3 years": 19.62,
            "Category average (Equity Mid Cap)": 16.0,
            "Rank (Equity Mid Cap)": 6.0,
            "Max Financial Services Ltd.": 4.37,
            "AU Small Finance Bank Ltd.": 4.24,
            "The Federal Bank Ltd.": 3.87,
            "Glenmark Pharmaceuticals Ltd.": 3.41,
            "Indian Bank": 3.31,
            "Balkrishna Industries Ltd.": 3.25,
            "Fortis Healthcare Ltd.": 3.16,
            "Vishal Mega Mart Ltd.": 2.92,
            "Ipca Laboratories Ltd.": 2.92,
            "Cummins India Ltd.": 2.5,
            "Marico Ltd.": 2.48,
            "Hindustan Petroleum Corporation Ltd.": 2.2,
            "1 year": 2.15,
            "Mahindra & Mahindra Financial Services Ltd.": 2.05,
            "Coforge Ltd.": 1.97,
            "Aurobindo Pharma Ltd.": 1.96,
            "Jindal Steel Ltd.": 1.9,
            "Tata Communications Ltd.": 1.86,
            "Apollo Tyres Ltd.": 1.81,
            "Alkem Laboratories Ltd.": 1.8,
        },
    },
    -51: {
        "family_id": -51, "name": "HDFC Prudence",
        "category": "Aggressive Hybrid", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Fund returns": 17.2,
            "Category average (Hybrid Aggressive Hybrid)": 13.9,
            "ICICI Bank Ltd.": 7.71,
            "Infosys Ltd.": 7.03,
            "State Bank of India": 6.55,
            "Larsen & Toubro Ltd.": 6.22,
            "7.4 Tata Sons Ltd. Aug 16 2022": 4.3,
            "8.75 State Bank of India": 3.86,
            "Power Grid Corporation of India Ltd.": 3.54,
            "NTPC Ltd.": 3.48,
            "8.85 HDFC Bank Ltd.": 2.66,
            "Gail (India) Ltd.": 2.45,
            "Axis Bank Ltd.": 2.37,
            "Tata Steel Ltd.": 1.96,
            "Vedanta Ltd.": 1.76,
            "8.6 Canara Bank Ltd.": 1.74,
            "HDFC Bank Ltd.": 1.59,
            "Power Finance Corporation Ltd.": 1.55,
            "Current Assets": 1.38,
            "Aurobindo Pharma Ltd.": 1.35,
            "8.15 State Bank of India": 1.28,
            "8.98 Punjab National Bank": 1.15,
            "Punjab National Bank": 1.14,
            "Tata Chemicals Ltd.": 1.07,
            "Avenue Supermarts Ltd.": 0.93,
        },
    },
    -52: {
        "family_id": -52, "name": "DSP Regular Savings",
        "category": "Aggressive Hybrid", "amc": "DSP Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 50.88,
            "5 years": 21.93,
            "Rank (Hybrid Conservative Hybrid)": 13.0,
            "GOI": 11.82,
            "3 years": 10.7,
            "GOI": 8.77,
            "Fund returns": 8.4,
            "Maharashtra State": 8.11,
            "Category average (Hybrid Conservative Hybrid)": 7.8,
            "GOI": 5.69,
            "GOI": 5.4,
            "Small Industries Devp. Bank of India Ltd.": 5.3,
            "IDFC First Bank Ltd.": 5.28,
            "Muthoot Finance Ltd.": 4.19,
            "Cholamandalam Investment and Finance Company Ltd.": 2.95,
            "GOI": 2.94,
            "HDFC Bank Ltd.": 2.89,
            "GOI": 2.89,
            "GOI": 2.87,
            "GOI": 2.85,
            "GOI": 2.82,
            "HDFC Bank Ltd.": 2.65,
            "ICICI Bank Ltd.": 1.56,
            "1 year": 1.31,
            "ITC Ltd.": 1.31,
        },
    },
    -53: {
        "family_id": -53, "name": "HDFC Large Cap",
        "category": "Large Cap", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 90.77,
            "5 years": 25.75,
            "Category average (Equity Large Cap)": 13.2,
            "Fund returns": 13.0,
            "Rank (Equity Large Cap)": 12.0,
            "ICICI Bank Ltd.": 9.15,
            "HDFC Bank Ltd.": 7.84,
            "Bharti Airtel Ltd.": 5.9,
            "Reliance Industries Ltd.": 5.61,
            "Kotak Mahindra Bank Ltd.": 5.47,
            "3 years": 4.75,
            "Titan Company Ltd.": 4.74,
            "Axis Bank Ltd.": 3.56,
            "Torrent Pharmaceuticals Ltd.": 3.49,
            "Infosys Ltd.": 3.01,
            "Bajaj Auto Ltd.": 2.95,
            "Lupin Ltd.": 2.79,
            "Bajaj Finserv Ltd.": 2.73,
            "Ambuja Cements Ltd.": 2.6,
            "State Bank of India": 2.43,
            "NTPC Ltd.": 2.34,
            "Cholamandalam Investment and Finance Company Ltd.": 2.15,
            "Eternal Ltd.": 1.96,
            "Tata Motors Ltd.": 1.84,
            "Max Healthcare Institute Ltd.": 1.72,
        },
    },
    -54: {
        "family_id": -54, "name": "DSP Aggressive Hybrid",
        "category": "Aggressive Hybrid", "amc": "DSP Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 88.17,
            "5 years": 26.8,
            "Fund returns": 13.2,
            "Category average (Hybrid Aggressive Hybrid)": 12.0,
            "Rank (Hybrid Aggressive Hybrid)": 10.0,
            "HDFC Bank Ltd.": 8.69,
            "3 years": 8.68,
            "ICICI Bank Ltd.": 5.94,
            "ITC Ltd.": 4.49,
            "GOI": 4.12,
            "Cipla Ltd.": 3.89,
            "Axis Bank Ltd.": 3.73,
            "Mahindra & Mahindra Ltd.": 3.62,
            "Kotak Mahindra Bank Ltd.": 3.61,
            "SBI Life Insurance Company Ltd.": 2.52,
            "DSP Short Term Fund Direct Plan-Growth": 2.3,
            "Samvardhana Motherson International Ltd.": 2.28,
            "Infosys Ltd.": 2.25,
            "Chhattisgarh State": 1.94,
            "Emami Ltd.": 1.8,
            "HDFC Life Insurance Co Ltd.": 1.57,
            "Maruti Suzuki India Ltd.": 1.55,
            "Torrent Pharmaceuticals Ltd.": 1.52,
            "GOI": 1.36,
            "Alkem Laboratories Ltd.": 1.32,
        },
    },
    -55: {
        "family_id": -55, "name": "Tata Aggressive Hybrid",
        "category": "Aggressive Hybrid", "amc": "Tata Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 72.93,
            "5 years": 21.83,
            "Rank (Hybrid Aggressive Hybrid)": 20.0,
            "Fund returns": 12.5,
            "Category average (Hybrid Aggressive Hybrid)": 12.0,
            "3 years": 6.55,
            "Bharti Airtel Ltd.": 5.13,
            "ICICI Bank Ltd.": 5.01,
            "Larsen & Toubro Ltd.": 4.15,
            "State Bank of India": 3.32,
            "Reliance Industries Ltd.": 2.96,
            "Ultratech Cement Ltd.": 2.58,
            "Infosys Ltd.": 2.53,
            "Tata Consultancy Services Ltd.": 2.48,
            "Kotak Mahindra Bank Ltd.": 2.48,
            "HDFC Bank Ltd.": 2.4,
            "Varun Beverages Ltd.": 2.25,
            "RBL Bank Ltd.": 2.18,
            "Maharashtra State": 2.16,
            "Mahindra & Mahindra Ltd.": 2.08,
            "Bank Of Baroda": 2.05,
            "ITC Ltd.": 2.04,
            "Axis Bank Ltd.": 1.97,
            "Torrent Pharmaceuticals Ltd.": 1.91,
            "PI Industries Ltd.": 1.77,
        },
    },
    -56: {
        "family_id": -56, "name": "HDFC ELSS Tax Saver",
        "category": "ELSS", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 37.08,
            "Fund returns": 14.0,
            "Category average (Equity ELSS)": 14.0,
            "Rank (Equity ELSS)": 13.0,
            "ICICI Bank Ltd.": 8.93,
            "3 years": 8.89,
            "HDFC Bank Ltd.": 8.23,
            "Axis Bank Ltd.": 7.22,
            "State Bank of India": 4.81,
            "Maruti Suzuki India Ltd.": 4.71,
            "Bharti Airtel Ltd.": 4.59,
            "Kotak Mahindra Bank Ltd.": 4.31,
            "SBI Life Insurance Company Ltd.": 3.51,
            "Reliance Industries Ltd.": 3.06,
            "HCL Technologies Ltd.": 2.76,
            "Hyundai Motor India Ltd.": 2.34,
            "Power Grid Corporation Of India Ltd.": 2.25,
            "Tata Steel Ltd.": 2.04,
            "Infosys Ltd.": 2.02,
            "Bajaj Auto Ltd.": 1.93,
            "Britannia Industries Ltd.": 1.84,
            "Eternal Ltd.": 1.79,
            "JSW Steel Ltd.": 1.63,
            "Larsen & Toubro Ltd.": 1.63,
            "Apollo Hospitals Enterprise Ltd.": 1.35,
        },
    },
    -57: {
        "family_id": -57, "name": "HDFC Regular Savings",
        "category": "Index", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Fund returns": 8.9,
            "Category average (Debt Short Duration)": 5.9,
            "HPCL Mittal Energy Ltd.": 3.65,
            "Adani Transmission Ltd.": 3.2,
            "National Bank For Agriculture & Rural Development": 2.97,
            "Housing Development Finance Corpn. Ltd.": 2.86,
            "Adani Power Mundra Ltd.": 2.81,
            "NUVOCO Vistas Corp Ltd.": 2.5,
            "Vedanta Ltd.": 2.41,
            "TMF Holdings Ltd.": 2.15,
            "Indiabulls Housing Finance Ltd.": 1.94,
            "EID-Parry (India) Ltd.": 1.93,
            "National Bank For Agriculture & Rural Development": 1.92,
            "Tata Capital Financial Services Ltd.": 1.9,
            "PNB Housing Finance Ltd.": 1.88,
            "Vedanta Ltd.": 1.83,
            "Tata Motors Ltd.": 1.66,
            "L&T Infrastructure Finance Co. Ltd.": 1.63,
            "LIC Housing Finance Ltd.": 1.45,
            "Manav Investment & Trading Company Ltd.": 1.45,
            "Vedanta Ltd.": 1.44,
            "Housing Development Finance Corpn. Ltd.": 1.43,
            "Sadbhav Infrastructure Project Ltd.": 1.39,
            "Primat Infrapower & Multiventures Pvt. Ltd.": 1.37,
            "Tata Sky Ltd.": 1.28,
        },
    },
    -58: {
        "family_id": -58, "name": "DSP Focused",
        "category": "Flexi Cap", "amc": "DSP Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 92.03,
            "5 years": 31.23,
            "Rank (Equity Flexi Cap)": 28.0,
            "Category average (Equity Flexi Cap)": 13.5,
            "Fund returns": 13.0,
            "3 years": 9.89,
            "ICICI Bank Ltd.": 8.71,
            "HDFC Bank Ltd.": 8.31,
            "Axis Bank Ltd.": 5.25,
            "Bharti Airtel Ltd.": 4.21,
            "SBI Life Insurance Company Ltd.": 4.1,
            "Cholamandalam Investment and Finance Company Ltd.": 4.06,
            "The Phoenix Mills Ltd.": 3.96,
            "State Bank of India": 3.55,
            "Coforge Ltd.": 3.38,
            "Polycab India Ltd.": 3.33,
            "Ipca Laboratories Ltd.": 3.26,
            "Coromandel International Ltd.": 2.97,
            "Samvardhana Motherson International Ltd.": 2.97,
            "Century Plyboards (India) Ltd.": 2.91,
            "Bajaj Finance Ltd.": 2.85,
            "Infosys Ltd.": 2.69,
            "Power Finance Corporation Ltd.": 2.65,
            "Bharat Petroleum Corporation Ltd.": 2.56,
            "Kirloskar Oil Engines Ltd.": 2.37,
        },
    },
    -59: {
        "family_id": -59, "name": "DSP Savings",
        "category": "Index", "amc": "DSP Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 37.91,
            "5 years": 17.87,
            "Rank (Debt Money Market)": 17.0,
            "3 years": 10.19,
            "Fund returns": 7.0,
            "Category average (Debt Money Market)": 6.5,
            "Small Industries Devp. Bank of India Ltd.": 3.86,
            "Reserve Bank of India": 3.01,
            "Panatone Finvest Ltd": 2.9,
            "Punjab National Bank": 2.64,
            "1 year": 2.51,
            "National Bank For Agriculture & Rural Development": 2.17,
            "HDFC Bank Ltd.": 2.16,
            "Indian Bank": 2.12,
            "HDFC Bank Ltd.": 1.95,
            "HDFC Bank Ltd.": 1.93,
            "Canara Bank": 1.93,
            "Bank Of Baroda": 1.72,
            "Small Industries Devp. Bank of India Ltd.": 1.69,
            "Bank Of Baroda": 1.46,
            "Bank Of Baroda": 1.45,
            "HDFC Bank Ltd.": 1.45,
            "Indusind Bank Ltd.": 1.45,
            "Punjab National Bank": 1.45,
            "National Bank For Agriculture & Rural Development": 1.45,
        },
    },
    -60: {
        "family_id": -60, "name": "HDFC Equity Savings",
        "category": "Equity Savings", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 62.39,
            "5 years": 21.66,
            "Fund returns": 9.9,
            "3 years": 8.74,
            "Category average (Hybrid Equity Savings)": 8.4,
            "HDFC Bank Ltd.": 7.27,
            "Reliance Industries Ltd.": 6.1,
            "ICICI Bank Ltd.": 4.03,
            "NTPC Ltd.": 3.81,
            "Titan Company Ltd.": 3.68,
            "Larsen & Toubro Ltd.": 3.64,
            "Sun Pharmaceutical Industries Ltd.": 3.59,
            "GOI": 2.32,
            "Maruti Suzuki India Ltd.": 2.1,
            "Bharti Airtel Ltd.": 2.03,
            "GOI": 1.96,
            "State Bank of India": 1.87,
            "Adani Ports and Special Economic Zone Ltd.": 1.79,
            "Bajaj Finance Ltd.": 1.67,
            "Axis Bank Ltd.": 1.55,
            "Kotak Mahindra Bank Ltd.": 1.55,
            "Muthoot Finance Ltd.": 1.31,
            "Hindalco Industries Ltd.": 1.25,
            "State Bank of India": 1.21,
            "Tata Consultancy Services Ltd.": 1.08,
        },
    },
    -61: {
        "family_id": -61, "name": "Tata Large Cap",
        "category": "Large Cap", "amc": "Tata Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 93.91,
            "5 years": 28.17,
            "Category average (Equity Large Cap)": 13.2,
            "Fund returns": 13.1,
            "Rank (Equity Large Cap)": 13.0,
            "3 years": 9.23,
            "ICICI Bank Ltd.": 8.65,
            "HDFC Bank Ltd.": 6.24,
            "Bharti Airtel Ltd.": 5.93,
            "Reliance Industries Ltd.": 5.59,
            "Axis Bank Ltd.": 3.87,
            "Kotak Mahindra Bank Ltd.": 3.56,
            "Larsen & Toubro Ltd.": 3.48,
            "Infosys Ltd.": 3.33,
            "State Bank of India": 3.26,
            "Bajaj Finance Ltd.": 2.96,
            "Tata Consultancy Services Ltd.": 2.78,
            "Mahindra & Mahindra Ltd.": 2.73,
            "Adani Energy Solutions Ltd.": 2.29,
            "Samvardhana Motherson International Ltd.": 2.19,
            "Interglobe Aviation Ltd.": 2.08,
            "Tech Mahindra Ltd.": 2.08,
            "Hindustan Unilever Ltd.": 2.05,
            "HDFC Asset Management Company Ltd.": 2.02,
            "JSW Steel Ltd.": 2.02,
        },
    },
    -62: {
        "family_id": -62, "name": "Tata Ethical",
        "category": "Thematic", "amc": "Tata Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 84.49,
            "5 years": 15.7,
            "Fund returns": 13.7,
            "Category average (Equity Thematic)": 13.6,
            "Infosys Ltd.": 7.88,
            "Tata Consultancy Services Ltd.": 5.19,
            "Rank (Equity Thematic)": 5.0,
            "Tech Mahindra Ltd.": 3.52,
            "Hindustan Unilever Ltd.": 3.46,
            "Jindal Steel Ltd.": 2.97,
            "Ultratech Cement Ltd.": 2.57,
            "Fortis Healthcare Ltd.": 2.49,
            "SRF Ltd.": 2.48,
            "Dr. Reddy's Laboratories Ltd.": 2.46,
            "Bharat Heavy Electricals Ltd.": 2.43,
            "Hero Motocorp Ltd.": 2.38,
            "HCL Technologies Ltd.": 2.37,
            "Hindalco Industries Ltd.": 2.24,
            "Alkem Laboratories Ltd.": 2.19,
            "Bharat Petroleum Corporation Ltd.": 2.11,
            "Crompton Greaves Consumer Electricals Ltd.": 2.11,
            "Nestle India Ltd.": 2.09,
            "Cipla Ltd.": 1.89,
            "Cummins India Ltd.": 1.78,
            "Britannia Industries Ltd.": 1.55,
        },
    },
    -63: {
        "family_id": -63, "name": "Tata Mid Cap",
        "category": "Mid Cap", "amc": "Tata Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 47.99,
            "Fund returns": 19.0,
            "3 years": 17.36,
            "Category average (Equity Mid Cap)": 16.0,
            "Rank (Equity Mid Cap)": 10.0,
            "1 year": 3.42,
            "Mankind Pharma Ltd.": 3.21,
            "The Federal Bank Ltd.": 3.07,
            "Bharat Heavy Electricals Ltd.": 2.9,
            "Indian Bank": 2.79,
            "Indusind Bank Ltd.": 2.78,
            "AU Small Finance Bank Ltd.": 2.72,
            "Max Financial Services Ltd.": 2.69,
            "UPL Ltd.": 2.63,
            "Glenmark Pharmaceuticals Ltd.": 2.58,
            "Marico Ltd.": 2.42,
            "Indus Towers Ltd.": 2.27,
            "One97 Communications Ltd.": 2.15,
            "Mphasis Ltd.": 2.04,
            "L&T Finance Ltd.": 2.0,
            "UNO Minda Ltd.": 1.99,
            "BSE Ltd.": 1.95,
            "Bharti Hexacom Ltd.": 1.9,
            "ICICI Lombard General Insurance Company Ltd.": 1.89,
            "Bharat Forge Ltd.": 1.85,
        },
    },
    -64: {
        "family_id": -64, "name": "DSP Short Term",
        "category": "Aggressive Hybrid", "amc": "DSP Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 40.46,
            "5 years": 17.54,
            "Rank (Debt Short Duration)": 10.0,
            "3 years": 9.84,
            "Fund returns": 7.7,
            "Category average (Debt Short Duration)": 6.6,
            "GOI": 5.81,
            "India Universal Trust AL1": 4.26,
            "Bharti Telecom Ltd.": 4.13,
            "National Bank For Agriculture & Rural Development": 3.85,
            "Karnataka State": 3.84,
            "Gujarat State": 3.73,
            "GOI": 3.66,
            "Knowledge Realty Trust": 3.08,
            "Muthoot Finance Ltd.": 2.83,
            "Jamnagar Utilities and Power Pvt. Ltd.": 2.45,
            "National Bank For Agriculture & Rural Development": 2.41,
            "India Infrastructure Finance Company Ltd.": 2.39,
            "Export-Import Bank Of India": 2.35,
            "Indian Railway Finance Corporation Ltd.": 2.32,
            "Bajaj Finance Ltd.": 2.3,
            "Power Finance Corporation Ltd.": 2.06,
            "Torrent Power Ltd.": 1.86,
            "1 year": 1.67,
            "Bajaj Finance Ltd.": 1.63,
        },
    },
    -65: {
        "family_id": -65, "name": "Tata Value",
        "category": "Value", "amc": "Tata Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 36.8,
            "Fund returns": 16.3,
            "Category average (Equity Value Oriented)": 14.7,
            "3 years": 9.47,
            "ICICI Bank Ltd.": 7.94,
            "Rank (Equity Value Oriented)": 7.0,
            "Shriram Finance Ltd": 5.37,
            "Kotak Mahindra Bank Ltd.": 5.02,
            "Muthoot Finance Ltd.": 4.95,
            "Coal India Ltd.": 4.84,
            "Indus Towers Ltd.": 4.6,
            "Motilal Oswal Financial Services Ltd.": 4.09,
            "NTPC Ltd.": 3.76,
            "Bharat Petroleum Corporation Ltd.": 3.75,
            "Hero Motocorp Ltd.": 3.47,
            "ITC Ltd.": 3.36,
            "Radico Khaitan Ltd.": 3.16,
            "Power Grid Corporation Of India Ltd.": 2.7,
            "Oil India Ltd.": 2.37,
            "Dixon Technologies (India) Ltd.": 2.34,
            "Eternal Ltd.": 2.23,
            "HDFC Bank Ltd.": 2.15,
            "Power Finance Corporation Ltd.": 1.93,
            "Ceat Ltd.": 1.84,
            "Premier Energies Ltd.": 1.71,
        },
    },
    -66: {
        "family_id": -66, "name": "Tata Dividend Yield",
        "category": "Thematic", "amc": "Tata Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 44.0,
            "Category average (Equity Thematic)": 19.4,
            "3 years": 17.81,
            "Fund returns": 15.8,
            "1 year": 4.88,
            "Rank (Equity Thematic)": 4.0,
            "ICICI Bank Ltd.": 3.35,
            "Larsen & Toubro Ltd.": 3.18,
            "HDFC Bank Ltd.": 3.15,
            "6 months": 3.04,
            "Bharat Electronics Ltd.": 2.65,
            "PNB Housing Finance Ltd.": 2.63,
            "Radico Khaitan Ltd.": 2.62,
            "State Bank of India": 2.43,
            "Power Grid Corporation Of India Ltd.": 2.18,
            "NTPC Ltd.": 2.03,
            "Navin Fluorine International Ltd.": 1.99,
            "Reliance Industries Ltd.": 1.97,
            "HDFC Asset Management Company Ltd.": 1.96,
            "RBL Bank Ltd.": 1.95,
            "Multi Commodity Exchange Of India Ltd.": 1.92,
            "Indian Bank": 1.85,
            "Adani Power Ltd.": 1.83,
            "Bharti Airtel Ltd.": 1.79,
            "Shriram Finance Ltd": 1.77,
        },
    },
    -67: {
        "family_id": -67, "name": "DSP ELSS Tax Saver",
        "category": "ELSS", "amc": "DSP Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 35.89,
            "Fund returns": 16.6,
            "Category average (Equity ELSS)": 14.0,
            "3 years": 11.3,
            "ICICI Bank Ltd.": 8.57,
            "HDFC Bank Ltd.": 8.17,
            "Axis Bank Ltd.": 6.61,
            "Rank (Equity ELSS)": 6.0,
            "State Bank of India": 4.53,
            "Bharti Airtel Ltd.": 3.45,
            "Kotak Mahindra Bank Ltd.": 2.66,
            "Infosys Ltd.": 2.58,
            "Mahindra & Mahindra Ltd.": 2.43,
            "Samvardhana Motherson International Ltd.": 2.4,
            "Tata Consultancy Services Ltd.": 2.24,
            "NTPC Ltd.": 1.91,
            "Max Financial Services Ltd.": 1.78,
            "Cipla Ltd.": 1.74,
            "Indus Towers Ltd.": 1.63,
            "Ipca Laboratories Ltd.": 1.62,
            "Asian Paints Ltd.": 1.62,
            "Hindustan Unilever Ltd.": 1.57,
            "Larsen & Toubro Ltd.": 1.54,
            "Tata Capital Ltd.": 1.46,
            "Bharat Petroleum Corporation Ltd.": 1.46,
        },
    },
    -68: {
        "family_id": -68, "name": "Tata Infrastructure",
        "category": "Sectoral", "amc": "Tata Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "5 years": 48.52,
            "Category average (Equity Sectoral)": 15.4,
            "Fund returns": 15.1,
            "3 years": 14.55,
            "Rank (Equity Sectoral)": 13.0,
            "Larsen & Toubro Ltd.": 6.74,
            "1 year": 6.72,
            "NTPC Ltd.": 4.45,
            "Adani Ports and Special Economic Zone Ltd.": 3.66,
            "Adani Energy Solutions Ltd.": 3.36,
            "Adani Power Ltd.": 3.19,
            "The Ramco Cements Ltd.": 3.12,
            "Interglobe Aviation Ltd.": 2.89,
            "Bharat Heavy Electricals Ltd.": 2.66,
            "Ultratech Cement Ltd.": 2.63,
            "Cummins India Ltd.": 2.18,
            "ABB India Ltd.": 2.13,
            "ZF Commercial Vehicle Control Systems India Ltd.": 2.09,
            "DEE Development Engineers Ltd.": 2.0,
            "Power Grid Corporation Of India Ltd.": 1.98,
            "Torrent Power Ltd.": 1.89,
            "Schaeffler India Ltd.": 1.83,
            "Data Patterns (India) Ltd.": 1.82,
            "DLF Ltd.": 1.8,
            "Indus Towers Ltd.": 1.78,
        },
    },
    -69: {
        "family_id": -69, "name": "DSP Large Cap",
        "category": "Large Cap", "amc": "DSP Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "10 years": 85.03,
            "5 years": 29.21,
            "Rank (Equity Large Cap)": 29.0,
            "Category average (Equity Large Cap)": 13.2,
            "Fund returns": 11.6,
            "HDFC Bank Ltd.": 9.29,
            "3 years": 8.47,
            "ICICI Bank Ltd.": 8.23,
            "ITC Ltd.": 7.18,
            "Axis Bank Ltd.": 5.64,
            "Infosys Ltd.": 5.08,
            "Mahindra & Mahindra Ltd.": 5.05,
            "Kotak Mahindra Bank Ltd.": 5.03,
            "Cipla Ltd.": 4.84,
            "Bharti Airtel Ltd.": 4.11,
            "NTPC Ltd.": 3.56,
            "Samvardhana Motherson International Ltd.": 3.15,
            "HDFC Life Insurance Co Ltd.": 2.85,
            "SBI Life Insurance Company Ltd.": 2.65,
            "Bajaj Finance Ltd.": 2.51,
            "Maruti Suzuki India Ltd.": 2.32,
            "State Bank of India": 1.8,
            "Oil And Natural Gas Corporation Ltd.": 1.76,
            "GAIL (India) Ltd.": 1.63,
            "Syngene International Ltd.": 1.46,
        },
    },
}
