"""
snapshot.py — Last-known-good fallback dataset
================================================
Bundled holdings for popular Indian equity schemes. Used when the
primary live data source (MFData.in) is unavailable.

Negative family_ids distinguish snapshot entries from live MFData.in IDs
(which are always positive). Frontend doesn't need to know — backend
routes /api/holdings/<id> appropriately.

To refresh: while MFData.in is up, run scripts/build_snapshot.py
(future — for now this file is hand-curated).
"""

SNAPSHOT_DATE = "Apr 2026"

SNAPSHOT_SCHEMES = {
    -1: {
        "family_id": -1, "name": "HDFC Flexi Cap Fund",
        "category": "Flexi Cap", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "ICICI Bank Ltd": 9.8, "HDFC Bank Ltd": 8.4, "Axis Bank Ltd": 6.1, "Cipla Ltd": 5.2,
            "SBI Life Insurance Co Ltd": 4.7, "Bharti Airtel Ltd": 4.5, "Infosys Ltd": 4.2,
            "Maruti Suzuki India Ltd": 3.8, "Hindalco Industries Ltd": 3.5, "Larsen & Toubro Ltd": 3.4,
            "HCL Technologies Ltd": 3.1, "Kotak Mahindra Bank Ltd": 2.9, "Piramal Pharma Ltd": 2.8,
            "Mphasis Ltd": 2.5, "ITC Ltd": 2.3, "State Bank of India": 2.1, "Hero MotoCorp Ltd": 1.9,
            "Apollo Hospitals Enterprise Ltd": 1.8, "Coal India Ltd": 1.7, "NTPC Ltd": 1.5,
        },
    },
    -2: {
        "family_id": -2, "name": "Parag Parikh Flexi Cap Fund",
        "category": "Flexi Cap", "amc": "PPFAS Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 7.9, "Bajaj Holdings and Investment Ltd": 7.5, "Power Grid Corp Of India Ltd": 6.2,
            "ITC Ltd": 5.8, "Coal India Ltd": 4.9, "ICICI Bank Ltd": 4.6,
            "Microsoft Corp": 4.2, "Meta Platforms Inc Class A": 4.0, "Alphabet Inc Class A": 3.8,
            "Amazon.com Inc": 3.5, "Maruti Suzuki India Ltd": 3.3, "HCL Technologies Ltd": 3.1,
            "Infosys Ltd": 2.9, "ICRA Ltd": 2.7, "IPCA Laboratories Ltd": 2.5,
            "Cipla Ltd": 2.3, "Indian Energy Exchange Ltd": 2.0, "Mahindra & Mahindra Ltd": 1.8,
            "Multi Commodity Exchange Of India Ltd": 1.6, "Zydus Lifesciences Ltd": 1.5,
        },
    },
    -3: {
        "family_id": -3, "name": "HDFC Top 100 Fund",
        "category": "Large Cap", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "ICICI Bank Ltd": 9.2, "HDFC Bank Ltd": 8.7, "Reliance Industries Ltd": 7.4,
            "Infosys Ltd": 6.1, "Axis Bank Ltd": 5.5, "Larsen & Toubro Ltd": 5.2, "Bharti Airtel Ltd": 4.8,
            "Tata Consultancy Services Ltd": 4.3, "ITC Ltd": 3.9, "State Bank of India": 3.6,
            "Maruti Suzuki India Ltd": 3.2, "NTPC Ltd": 3.0, "Kotak Mahindra Bank Ltd": 2.7,
            "HCL Technologies Ltd": 2.5, "Hindustan Unilever Ltd": 2.2, "Sun Pharmaceutical Industries Ltd": 2.0,
            "Mahindra & Mahindra Ltd": 1.9, "Power Grid Corp Of India Ltd": 1.7,
            "Asian Paints Ltd": 1.5, "UltraTech Cement Ltd": 1.4,
        },
    },
    -4: {
        "family_id": -4, "name": "ICICI Prudential Bluechip Fund",
        "category": "Large Cap", "amc": "ICICI Prudential Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 9.5, "ICICI Bank Ltd": 8.8, "Reliance Industries Ltd": 7.1,
            "Infosys Ltd": 5.6, "Larsen & Toubro Ltd": 5.0, "Axis Bank Ltd": 4.5, "Bharti Airtel Ltd": 4.3,
            "Tata Consultancy Services Ltd": 4.0, "Mahindra & Mahindra Ltd": 3.6,
            "Maruti Suzuki India Ltd": 3.3, "ITC Ltd": 3.1, "State Bank of India": 2.9,
            "HCL Technologies Ltd": 2.6, "Sun Pharmaceutical Industries Ltd": 2.4,
            "NTPC Ltd": 2.2, "Kotak Mahindra Bank Ltd": 2.0, "UltraTech Cement Ltd": 1.8,
            "Power Grid Corp Of India Ltd": 1.7, "Bajaj Finance Ltd": 1.5, "Hindustan Unilever Ltd": 1.4,
        },
    },
    -5: {
        "family_id": -5, "name": "SBI Bluechip Fund",
        "category": "Large Cap", "amc": "SBI Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 9.0, "ICICI Bank Ltd": 8.4, "Reliance Industries Ltd": 6.8,
            "Infosys Ltd": 5.3, "Larsen & Toubro Ltd": 4.7, "Bharti Airtel Ltd": 4.5, "Axis Bank Ltd": 4.2,
            "Tata Consultancy Services Ltd": 3.9, "ITC Ltd": 3.5, "State Bank of India": 3.3,
            "Maruti Suzuki India Ltd": 3.0, "Kotak Mahindra Bank Ltd": 2.8, "HCL Technologies Ltd": 2.5,
            "Mahindra & Mahindra Ltd": 2.3, "Sun Pharmaceutical Industries Ltd": 2.0,
            "NTPC Ltd": 1.8, "Hindustan Unilever Ltd": 1.6, "Bajaj Finance Ltd": 1.5,
            "Asian Paints Ltd": 1.3, "UltraTech Cement Ltd": 1.2,
        },
    },
    -6: {
        "family_id": -6, "name": "Mirae Asset Large Cap Fund",
        "category": "Large Cap", "amc": "Mirae Asset Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 9.3, "ICICI Bank Ltd": 8.5, "Reliance Industries Ltd": 7.0,
            "Infosys Ltd": 5.9, "Bharti Airtel Ltd": 4.7, "Axis Bank Ltd": 4.3, "Larsen & Toubro Ltd": 4.1,
            "Tata Consultancy Services Ltd": 3.8, "Maruti Suzuki India Ltd": 3.4,
            "Mahindra & Mahindra Ltd": 3.1, "ITC Ltd": 2.9, "State Bank of India": 2.7,
            "HCL Technologies Ltd": 2.5, "Sun Pharmaceutical Industries Ltd": 2.2,
            "Kotak Mahindra Bank Ltd": 2.0, "NTPC Ltd": 1.8, "UltraTech Cement Ltd": 1.6,
            "Bajaj Finance Ltd": 1.5, "Hindustan Unilever Ltd": 1.4, "Titan Company Ltd": 1.3,
        },
    },
    -7: {
        "family_id": -7, "name": "Axis Bluechip Fund",
        "category": "Large Cap", "amc": "Axis Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 9.6, "ICICI Bank Ltd": 8.2, "Reliance Industries Ltd": 6.5,
            "Bajaj Finance Ltd": 5.8, "Infosys Ltd": 5.4, "Tata Consultancy Services Ltd": 4.6,
            "Bharti Airtel Ltd": 4.4, "Avenue Supermarts Ltd": 4.2, "Tata Consumer Products Ltd": 3.9,
            "Titan Company Ltd": 3.7, "Asian Paints Ltd": 3.4, "Nestle India Ltd": 3.1,
            "Maruti Suzuki India Ltd": 2.8, "Pidilite Industries Ltd": 2.5,
            "Cholamandalam Investment and Finance Company Ltd": 2.2, "Kotak Mahindra Bank Ltd": 2.0,
            "Divi's Laboratories Ltd": 1.8, "Sun Pharmaceutical Industries Ltd": 1.6,
            "Info Edge (India) Ltd": 1.4, "Larsen & Toubro Ltd": 1.3,
        },
    },
    -8: {
        "family_id": -8, "name": "Kotak Flexicap Fund",
        "category": "Flexi Cap", "amc": "Kotak Mahindra Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 8.9, "ICICI Bank Ltd": 7.8, "Reliance Industries Ltd": 6.4,
            "Infosys Ltd": 5.2, "Larsen & Toubro Ltd": 4.8, "Bharti Airtel Ltd": 4.5, "Axis Bank Ltd": 4.2,
            "Tata Consultancy Services Ltd": 3.6, "Maruti Suzuki India Ltd": 3.3,
            "ITC Ltd": 3.0, "State Bank of India": 2.8, "Bajaj Finance Ltd": 2.5,
            "Coforge Ltd": 2.3, "Mahindra & Mahindra Ltd": 2.1, "HCL Technologies Ltd": 1.9,
            "Persistent Systems Ltd": 1.7, "Cholamandalam Investment and Finance Company Ltd": 1.5,
            "Sun Pharmaceutical Industries Ltd": 1.4, "Titan Company Ltd": 1.3, "NTPC Ltd": 1.2,
        },
    },
    -9: {
        "family_id": -9, "name": "HDFC Mid-Cap Opportunities Fund",
        "category": "Mid Cap", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Max Financial Services Ltd": 4.2, "Apollo Hospitals Enterprise Ltd": 3.8,
            "The Federal Bank Ltd": 3.5, "Coforge Ltd": 3.2,
            "Cholamandalam Investment and Finance Company Ltd": 3.0, "Bharat Forge Ltd": 2.8,
            "Persistent Systems Ltd": 2.6, "AU Small Finance Bank Ltd": 2.4,
            "Page Industries Ltd": 2.2, "Cummins India Ltd": 2.1, "Trent Ltd": 2.0,
            "Voltas Ltd": 1.9, "The Indian Hotels Company Ltd": 1.8, "Polycab India Ltd": 1.7,
            "Tube Investments of India Ltd": 1.6, "Astral Ltd": 1.5,
            "Hindustan Petroleum Corp Ltd": 1.4, "Bajaj Holdings and Investment Ltd": 1.3,
            "Mphasis Ltd": 1.2, "Container Corporation of India Ltd": 1.1,
        },
    },
    -10: {
        "family_id": -10, "name": "Axis Midcap Fund",
        "category": "Mid Cap", "amc": "Axis Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Cholamandalam Investment and Finance Company Ltd": 4.5, "Trent Ltd": 4.1, "Coforge Ltd": 3.8,
            "Persistent Systems Ltd": 3.5, "Max Financial Services Ltd": 3.2,
            "Page Industries Ltd": 2.9, "Astral Ltd": 2.7, "Polycab India Ltd": 2.5,
            "Tube Investments of India Ltd": 2.3, "AU Small Finance Bank Ltd": 2.1,
            "Apollo Hospitals Enterprise Ltd": 1.9, "The Federal Bank Ltd": 1.8, "Bharat Forge Ltd": 1.7,
            "Voltas Ltd": 1.6, "Pidilite Industries Ltd": 1.5, "Mphasis Ltd": 1.4,
            "Cummins India Ltd": 1.3, "PI Industries Ltd": 1.2, "The Indian Hotels Company Ltd": 1.1,
            "Crompton Greaves Consumer Electricals Ltd": 1.0,
        },
    },
    -11: {
        "family_id": -11, "name": "Nippon India Small Cap Fund",
        "category": "Small Cap", "amc": "Nippon India Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Tube Investments of India Ltd": 3.2, "Multi Commodity Exchange Of India Ltd": 2.8,
            "KEI Industries Ltd": 2.5, "Cera Sanitaryware Ltd": 2.3,
            "Carborundum Universal Ltd": 2.1, "Karur Vysya Bank Ltd": 1.9,
            "City Union Bank Ltd": 1.7, "ELGI Equipments Ltd": 1.6, "Apar Industries Ltd": 1.5,
            "Kirloskar Oil Engines Ltd": 1.4, "Greenply Industries Ltd": 1.3,
            "Voltamp Transformers Ltd": 1.2, "Birlasoft Ltd": 1.1, "Triveni Turbine Ltd": 1.0,
            "Praj Industries Ltd": 0.9, "Greaves Cotton Ltd": 0.9,
            "Eveready Industries India Ltd": 0.8, "JB Chemicals & Pharmaceuticals Ltd": 0.8,
            "Schaeffler India Ltd": 0.7, "Tata Investment Corp Ltd": 0.7,
        },
    },
    -12: {
        "family_id": -12, "name": "SBI Small Cap Fund",
        "category": "Small Cap", "amc": "SBI Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Cera Sanitaryware Ltd": 3.4, "Tube Investments of India Ltd": 3.1, "KEI Industries Ltd": 2.8,
            "Carborundum Universal Ltd": 2.6, "City Union Bank Ltd": 2.3,
            "Multi Commodity Exchange Of India Ltd": 2.1, "ELGI Equipments Ltd": 1.9,
            "Apar Industries Ltd": 1.7, "Karur Vysya Bank Ltd": 1.6,
            "Voltamp Transformers Ltd": 1.5, "Triveni Turbine Ltd": 1.4,
            "Greenply Industries Ltd": 1.3, "Praj Industries Ltd": 1.2,
            "Birlasoft Ltd": 1.1, "JB Chemicals & Pharmaceuticals Ltd": 1.0,
            "Schaeffler India Ltd": 0.9, "Kirloskar Oil Engines Ltd": 0.9,
            "Tata Investment Corp Ltd": 0.8, "Greaves Cotton Ltd": 0.7,
            "Cholamandalam Investment and Finance Company Ltd": 0.6,
        },
    },
    -13: {
        "family_id": -13, "name": "Axis Small Cap Fund",
        "category": "Small Cap", "amc": "Axis Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "KEI Industries Ltd": 3.5, "Tube Investments of India Ltd": 3.2, "Birlasoft Ltd": 2.9,
            "Multi Commodity Exchange Of India Ltd": 2.6, "Carborundum Universal Ltd": 2.4,
            "Cera Sanitaryware Ltd": 2.2, "ELGI Equipments Ltd": 2.0,
            "City Union Bank Ltd": 1.8, "Apar Industries Ltd": 1.6,
            "Karur Vysya Bank Ltd": 1.5, "Voltamp Transformers Ltd": 1.4,
            "Praj Industries Ltd": 1.3, "Triveni Turbine Ltd": 1.2,
            "Greenply Industries Ltd": 1.1, "JB Chemicals & Pharmaceuticals Ltd": 1.0,
            "Schaeffler India Ltd": 0.9, "Kirloskar Oil Engines Ltd": 0.8,
            "Tata Investment Corp Ltd": 0.7, "Eveready Industries India Ltd": 0.6,
            "Greaves Cotton Ltd": 0.5,
        },
    },
    -14: {
        "family_id": -14, "name": "Quant Small Cap Fund",
        "category": "Small Cap", "amc": "Quant Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "Reliance Industries Ltd": 5.2, "ITC Ltd": 4.6, "Adani Power Ltd": 4.1,
            "Tube Investments of India Ltd": 3.5, "Multi Commodity Exchange Of India Ltd": 3.0,
            "RBL Bank Ltd": 2.7, "Bikaji Foods International Ltd": 2.4,
            "Carborundum Universal Ltd": 2.1, "JK Cement Ltd": 1.9,
            "Aurobindo Pharma Ltd": 1.7, "Karur Vysya Bank Ltd": 1.5,
            "Apar Industries Ltd": 1.4, "City Union Bank Ltd": 1.3, "Birlasoft Ltd": 1.2,
            "ELGI Equipments Ltd": 1.1, "JB Chemicals & Pharmaceuticals Ltd": 1.0,
            "KEI Industries Ltd": 0.9, "Praj Industries Ltd": 0.8,
            "Greenply Industries Ltd": 0.7, "Schaeffler India Ltd": 0.6,
        },
    },
    -15: {
        "family_id": -15, "name": "Parag Parikh ELSS Tax Saver Fund",
        "category": "ELSS", "amc": "PPFAS Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 8.7, "Bajaj Holdings and Investment Ltd": 7.2, "ICICI Bank Ltd": 6.5,
            "Power Grid Corp Of India Ltd": 5.8, "Coal India Ltd": 5.1, "ITC Ltd": 4.6,
            "Maruti Suzuki India Ltd": 4.0, "Infosys Ltd": 3.6, "HCL Technologies Ltd": 3.3,
            "Cipla Ltd": 3.0, "ICRA Ltd": 2.7, "IPCA Laboratories Ltd": 2.4,
            "Mahindra & Mahindra Ltd": 2.2, "Persistent Systems Ltd": 2.0,
            "Multi Commodity Exchange Of India Ltd": 1.8, "Indian Energy Exchange Ltd": 1.6,
            "Zydus Lifesciences Ltd": 1.5, "Hero MotoCorp Ltd": 1.4,
            "Sun Pharmaceutical Industries Ltd": 1.3, "Tech Mahindra Ltd": 1.2,
        },
    },
    -16: {
        "family_id": -16, "name": "Mirae Asset ELSS Tax Saver Fund",
        "category": "ELSS", "amc": "Mirae Asset Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 9.1, "ICICI Bank Ltd": 8.3, "Reliance Industries Ltd": 6.7,
            "Infosys Ltd": 5.6, "Bharti Airtel Ltd": 4.5, "Axis Bank Ltd": 4.2,
            "Larsen & Toubro Ltd": 3.9, "Tata Consultancy Services Ltd": 3.6,
            "Maruti Suzuki India Ltd": 3.2, "Mahindra & Mahindra Ltd": 2.9, "ITC Ltd": 2.7,
            "State Bank of India": 2.5, "HCL Technologies Ltd": 2.3, "Coforge Ltd": 2.1,
            "Sun Pharmaceutical Industries Ltd": 1.9, "Kotak Mahindra Bank Ltd": 1.7,
            "Persistent Systems Ltd": 1.5, "Bajaj Finance Ltd": 1.3, "NTPC Ltd": 1.2,
            "Titan Company Ltd": 1.1,
        },
    },
    -17: {
        "family_id": -17, "name": "UTI Nifty 50 Index Fund",
        "category": "Index Funds", "amc": "UTI Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 13.0, "ICICI Bank Ltd": 8.4, "Reliance Industries Ltd": 8.1,
            "Infosys Ltd": 5.6, "Bharti Airtel Ltd": 4.0, "Tata Consultancy Services Ltd": 3.7,
            "Larsen & Toubro Ltd": 3.5, "ITC Ltd": 3.4, "Axis Bank Ltd": 3.0,
            "Mahindra & Mahindra Ltd": 2.7, "Kotak Mahindra Bank Ltd": 2.4, "State Bank of India": 2.3,
            "HCL Technologies Ltd": 2.0, "Maruti Suzuki India Ltd": 1.9,
            "Sun Pharmaceutical Industries Ltd": 1.7, "Bajaj Finance Ltd": 1.6,
            "NTPC Ltd": 1.5, "Hindustan Unilever Ltd": 1.4, "Titan Company Ltd": 1.3,
            "Asian Paints Ltd": 1.2,
        },
    },
    -18: {
        "family_id": -18, "name": "HDFC Nifty 50 Index Fund",
        "category": "Index Funds", "amc": "HDFC Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 13.0, "ICICI Bank Ltd": 8.4, "Reliance Industries Ltd": 8.1,
            "Infosys Ltd": 5.6, "Bharti Airtel Ltd": 4.0, "Tata Consultancy Services Ltd": 3.7,
            "Larsen & Toubro Ltd": 3.5, "ITC Ltd": 3.4, "Axis Bank Ltd": 3.0,
            "Mahindra & Mahindra Ltd": 2.7, "Kotak Mahindra Bank Ltd": 2.4, "State Bank of India": 2.3,
            "HCL Technologies Ltd": 2.0, "Maruti Suzuki India Ltd": 1.9,
            "Sun Pharmaceutical Industries Ltd": 1.7, "Bajaj Finance Ltd": 1.6,
            "NTPC Ltd": 1.5, "Hindustan Unilever Ltd": 1.4, "Titan Company Ltd": 1.3,
            "Asian Paints Ltd": 1.2,
        },
    },
    -19: {
        "family_id": -19, "name": "Nippon India Large Cap Fund",
        "category": "Large Cap", "amc": "Nippon India Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 8.7, "ICICI Bank Ltd": 8.1, "Reliance Industries Ltd": 6.9,
            "Infosys Ltd": 5.5, "Larsen & Toubro Ltd": 5.1, "ITC Ltd": 4.6, "Axis Bank Ltd": 4.3,
            "Bharti Airtel Ltd": 4.0, "Tata Consultancy Services Ltd": 3.7, "State Bank of India": 3.5,
            "Maruti Suzuki India Ltd": 3.2, "Mahindra & Mahindra Ltd": 2.9, "NTPC Ltd": 2.6,
            "HCL Technologies Ltd": 2.4, "Power Grid Corp Of India Ltd": 2.1,
            "Sun Pharmaceutical Industries Ltd": 1.9, "Coal India Ltd": 1.7,
            "Kotak Mahindra Bank Ltd": 1.5, "Oil & Natural Gas Corp Ltd": 1.4, "Tata Steel Ltd": 1.3,
        },
    },
    -20: {
        "family_id": -20, "name": "Canara Robeco Bluechip Equity Fund",
        "category": "Large Cap", "amc": "Canara Robeco Mutual Fund",
        "month": SNAPSHOT_DATE,
        "holdings": {
            "HDFC Bank Ltd": 9.4, "ICICI Bank Ltd": 8.6, "Reliance Industries Ltd": 7.2,
            "Infosys Ltd": 5.8, "Bharti Airtel Ltd": 4.9, "Larsen & Toubro Ltd": 4.5,
            "Axis Bank Ltd": 4.1, "Tata Consultancy Services Ltd": 3.8, "Bajaj Finance Ltd": 3.4,
            "Mahindra & Mahindra Ltd": 3.1, "Maruti Suzuki India Ltd": 2.9,
            "Kotak Mahindra Bank Ltd": 2.6, "Asian Paints Ltd": 2.3, "Titan Company Ltd": 2.1,
            "Nestle India Ltd": 1.9, "Sun Pharmaceutical Industries Ltd": 1.7, "ITC Ltd": 1.6,
            "HCL Technologies Ltd": 1.4, "Hindustan Unilever Ltd": 1.3, "State Bank of India": 1.2,
        },
    },
}
